### ISSUE TITLE
Server crash - Encountered an unexpected exception

### ISSUE THREAD

**Issue by luketeam5** [pl3xgaming/Purpur#1009]
### Timings link

N/A

### Stack trace

[Crash report](https://paste.gg/p/anonymous/babb49d709704a06bb0c82758e73a13f/files/aa93aa1995424049a83a462575b0a191/raw)

[Stack trace on paste.gg](https://paste.gg/p/anonymous/15d5c384bba744eea60144f367c02634/files/bbc2ce0072544ab592210d988344633c/raw)
```
[21:34:11 ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.serialize.SerializationException: [item-validation, book-size, page-max] of type java.lang.Integer: Value 9999999999999 is out of range for an integer ([-2147483648,2147483647])
        at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:247) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.lambda$creator$0(Configurations.java:79) ~[purpur-1.19.jar:git-Purpur-1669]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:113) ~[purpur-1.19.jar:git-Purpur-1669]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:97) ~[purpur-1.19.jar:git-Purpur-1669]
        at io.papermc.paper.configuration.PaperConfigurations.initializeGlobalConfiguration(PaperConfigurations.java:172) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:220) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1669]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:34:11 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$16(MinecraftServer.java:1720) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:61) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1719) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1240) ~[purpur-1.19.jar:git-Purpur-1669]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1669]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Purpur version

Current: Purpur-1669 (1.19)
Previous: Purpur-1628 (1.18.2)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
You've set the `page-max` option in Paper's config to `9999999999999`, which is out of the integer range. This isn't an issue with the server, rather a misconfigured setup.

For more info, view [Paper's config docs](https://docs.papermc.io/paper/reference/global-configuration#book-size).

**Comment by luketeam5** [comment]
> You've set the `page-max` option in Paper's config to `9999999999999`, which is out of the integer range. This isn't an issue with the server, rather a misconfigured setup.
> 
> For more info, view [Paper's config docs](https://docs.papermc.io/paper/reference/global-configuration#book-size).

I have `page-max` set to 2560

**Comment by BillyGalbreath** [comment]
> [21:34:11 ERROR]: Encountered an unexpected exception
> org.spongepowered.configurate.serialize.SerializationException: [item-validation, book-size, page-max] of type java.lang.Integer: Value 9999999999999 is out of range for an integer ([-2147483648,2147483647])
>         at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:247) ~[configurate-core-4.1.2.jar:?]

Let's take a closer look..
```
[21:34:11 ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.serialize.SerializationException: [item-validation, book-size, page-max] of type java.lang.Integer: Value 9999999999999 is out of range for an integer ([-2147483648,2147483647])
        at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:247) ~[configurate-core-4.1.2.jar:?]
```
No, closer...
```
SerializationException: [item-validation, book-size, page-max] of type java.lang.Integer: Value 9999999999999 is out of range for an integer ([-2147483648,2147483647])
        at
```
clooooseeeeer...
```
[item-validation, book-size, page-max] of type java.lang.Integer: Value 9999999999999 is out of range for an integer ([-2147483648,2147483647])
```
one more time...
```
Value 9999999999999 is out of range
```

**Comment by luketeam5** [comment]
Sorry for late reply, **I HAVE `page-max` in config set to 2560** not `9999999999999 `. I am certain that I don't have "misconfigured setup" and I think that Purpur is reading this config wrong for some reason.

![image](https://user-images.githubusercontent.com/40070133/174801165-5134cf95-e3f5-4e5a-b25e-a6afa8450ee2.png)
Here is screenshot from my config file if you still don't belive me.

**Comment by katekerllenevich** [comment]
Purpur doesn't change how paper reads the config.

**Comment by encode42** [comment]
Are you sure you're editing the right config file? Remember, Paper shuffled their config files around, and `paper.yml` no longer exists.

**Comment by luketeam5** [comment]
![image](https://user-images.githubusercontent.com/40070133/174862443-01d5ef92-ac40-4509-8915-0f9aed0a1e23.png)
I uninstalled Purpur and added Paper and it worked fine so I think that there may be some issue with Purpur.

**Comment by encode42** [comment]
Not once in Purpur or Pufferfish is `9999999999999` mentioned. `9999999999999` is a number that would be explicitly set, as `Integer.MAX_VALUE` returns `2147483647` (Developers use `Integer.MAX_VALUE` to signify "infinite"). `9999999999999` looks like a user spammed `9` to attempt to disable the option, but for too long.

Try to download your server's config files and do a mass search for "`9999999999999`". Applications such as Notepad++ have the ability to search file contents in a directory.
