### ISSUE TITLE
Spark java.nio.BufferUnderflowException losing profiler data

### ISSUE THREAD

**Issue by hitanol** [pl3xgaming/Purpur#1058]
### Spark link

https://spark.lucko.me/xoRB9qxMR5

### Expected behavior

It should print "The active profiler has been stopped! Uploading results...
[23:18:26 INFO]: [⚡] Profiler results:"

### Observed/Actual behavior

and not

"```
[23:18:18 INFO]: [⚡] The active profiler has been stopped! Uploading results...
[23:18:19 ERROR]: [spark] Exception occurred whilst executing a spark command
[23:18:19 WARN]: java.nio.BufferUnderflowException
[23:18:19 WARN]:        at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:699)
[23:18:19 WARN]:        at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:329)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.getVarint(JfrReader.java:455)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readConstantPool(JfrReader.java:280)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readChunk(JfrReader.java:216)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.<init>(JfrReader.java:80)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.AsyncSampler.aggregateOutput(AsyncSampler.java:186)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.sampler.async.AsyncSampler.toProto(AsyncSampler.java:166)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:308)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:302)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:136)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$8941/0x00000000b52ddd58.execute(Unknown Source)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:392)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:302)
[23:18:19 WARN]:        at spark.jar//me.lucko.spark.common.SparkPlatform$$Lambda$13379/0x00000000500108f8.run(Unknown Source)
[23:18:19 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:18:19 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:18:19 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:18:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:18:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:18:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
```"

### Steps/models to reproduce

spark profiler

wait your time...

spark profiler --stop

see the exception message

### Purpur version

git-Purpur-1713

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

_No response_

**Comment by hitanol** [comment]
idk if the issue is with spark or with purpur since its integrated by default

**Comment by BillyGalbreath** [comment]
Report this to spark. We just provide it, not integrate it.

**Comment by hitanol** [comment]
@lucko

**Comment by lucko** [comment]
> The profiler was running for 57m 30s 

You should be running the profiler for 10 minutes at most. 1-5m is best in my experience.
