### ISSUE TITLE
Permission denied. What to do?

### ISSUE THREAD

**Issue by Game2D** [pl3xgaming/Purpur#1061]
### Spark link

I don't know what it means

### Description of issue

Failed to save level ./world
java.io.IOException: Permission denied
at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
at java.io.File.createTempFile(File.java:2170) ~[?:?]
at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.saveDataTag(LevelStorageSource.java:402) ~[?:?]
at net.minecraft.server.level.ServerLevel.saveLevelDat(ServerLevel.java:1357) ~[?:?]
at net.minecraft.server.level.ServerLevel.save(ServerLevel.java:1346) ~[?:?]
at net.minecraft.server.MinecraftServer.saveAllChunks(MinecraftServer.java:893) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:927) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.commands.SaveAllCommand.saveAll(SaveAllCommand.java:27) ~[?:?]
at net.minecraft.server.commands.SaveAllCommand.lambda$register$1(SaveAllCommand.java:15) ~[?:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.18.2.jar:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178) ~[purpur-1.18.2.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:299) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[purpur-1.18.2.jar:git-Purpur-1632]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Purpur version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Kichura** [comment]
Caused by insufficient permissions assigned to the server, you will need to give the server permissions to manage data properly - otherwise this is something purpur cannot fix themselves.
