### ISSUE TITLE
Minecart Speed Error

### ISSUE THREAD

**Issue by LeeTheTech** [pl3xgaming/Purpur#1071]
### Spark link

https://spark.lucko.me/1b4QRs96WJ

### Expected behavior

It works as expected but it keeps throwing the following error:

```
[07:11:47 ERROR]: Entity threw exception at world:-2144.5,90.0,-6346.860002875313
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "speed" is null
        at net.minecraft.world.entity.vehicle.AbstractMinecart.getControllableSpeed(AbstractMinecart.java:515) ~[?:?]
        at net.minecraft.world.entity.vehicle.AbstractMinecart.comeOffTrack(AbstractMinecart.java:534) ~[?:?]
        at net.minecraft.world.entity.vehicle.AbstractMinecart.tick(AbstractMinecart.java:397) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1236) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:715) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.jar:git-Purpur-1730]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:693) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1580) ~[purpur-1.19.jar:git-Purpur-1730]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1730]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.jar:git-Purpur-1730]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1209) ~[purpur-1.19.jar:git-Purpur-1730]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1730]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:12:05 INFO]: Checking version, please wait...
[07:12:05 INFO]: Current: git-Purpur-1730 (MC: 1.19)*
Previous: git-Purpur-1723 (MC: 1.19)
```
* You are running the latest version

### Observed/Actual behavior

It works, just throwing an error.

### Steps/models to reproduce

minecart:
        max-speed: 0.5
        place-anywhere: true
        controllable:
          enabled: true
          step-height: 1.0
          hop-boost: 0.5
          fall-damage: false
          base-speed: 0.1
          block-speed:
            grass_block: 0.3
            stone: 0.5

### Purpur version

git-purpur-1730 1.19

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Sadly this is an error that happens at random times when using the minecart controllable feature. I'm sure there's a reason, just have not pinpointed it.

**Comment by BillyGalbreath** [comment]
I couldn't seem to replicate this error, even with your settings. But I changed the code where I see a possible npe could occur
