### ISSUE TITLE
Exception loading entity: ReportedException: Loading entity NBT

### ISSUE THREAD

**Issue by SrBedrock** [pl3xgaming/Purpur#11]
**Describe the bug**
Console error.

**To Reproduce**
I don't know how to reproduce.

**Screenshots or Videos**
```
>.... [23:42:55 WARN]: Exception loading entity:
net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT
at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1905) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:349) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:229) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:390) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:371) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:568) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ChunkRegionLoader.lambda$loadChunk$6(ChunkRegionLoader.java:169) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.Chunk.addEntities(Chunk.java:744) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$c$38(PlayerChunkMap.java:1345) ~[patched_1.15.2.jar:git-Purpur-491]
at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:164) ~[patched_1.15.2.jar:git-Purpur-491]
at com.mojang.datafixers.util.Either$Left.map(Either.java:39) ~[patched_1.15.2.jar:git-Purpur-491]
at com.mojang.datafixers.util.Either.mapLeft(Either.java:164) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$c$39(PlayerChunkMap.java:1328) ~[patched_1.15.2.jar:git-Purpur-491]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:999) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1011) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:536) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1125) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:957) ~[patched_1.15.2.jar:git-Purpur-491]
at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.AssertionError: TRAP
at net.minecraft.server.v1_15_R1.ItemStack.checkEmpty(ItemStack.java:114) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.ItemStack.setCount(ItemStack.java:933) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityEnderSignal.c(SourceFile:46) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:192) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityEnderSignal.b(SourceFile:46) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.EntityEnderSignal.a(SourceFile:194) ~[patched_1.15.2.jar:git-Purpur-491]
at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1820) ~[patched_1.15.2.jar:git-Purpur-491]
... 27 more
```

**Plugins**
>....=>.... [23:54:48 INFO]: Plugins (48): AntiCooldown, AuthMe, BuycraftX, ChatReaction, ChatReactionPlus, CheaperPhysicsEvent, ConsoleSpamFix, CoreProtect, CrazyCrates, DeluxeTags, EasyChairs, EntityDetection, Essentials, EssentialsSpawn, EZColors, eZProtector, F3Name, FarmLimiter, FastLogin, GriefPrevention, Guilds, HolographicDisplays, KillerMoney, Lottery, LuckPerms, mcMMO, ModReq, PlaceholderAPI, PlayerHeads, PlayerShopGUIPlus, ProtocolLib, PsudoCommand, ShopGUIPlus, SkinsRestorer, SpawnerManager, SuperbVote, TAB, TrMenu, UltimateChat, Vault, VKAutoPickup, VoidGenerator, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard, WorldLoader

**Version**
>....=>.... [23:54:20 INFO]: This server is running Purpur version git-Purpur-491 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [23:54:20 INFO]: Checking version, please wait...
>.... [23:54:20 INFO]: Previous version: git-Tuinity-"dd7a194" (MC: 1.15.2)
>.... [23:54:20 INFO]: You are running the latest version

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
I used Paper for a long time and I never saw this error

**Additional context**
Add any other context about the problem here you think will help resolve the problem.
![image](https://user-images.githubusercontent.com/51332006/77026944-a6464500-6973-11ea-9e35-3ac35be8187f.png)

**Comment by BillyGalbreath** [comment]
The error is from trying to load an eye of ender from disk (on chunk load) but it has an invalid item stored in it (probably a null item from a bad plugin)

**Comment by SrBedrock** [comment]
ok, thanks!
