### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by 4o4E** [pl3xgaming/Purpur#1102]
### Spark link

https://spark.lucko.me/KGMU1kWaKf

### Stack trace

The server crashed five times today and the stack trace is the same. Similar (stack trace) crashes often occur on 1.18

https://pastebin.com/td2d1LHQ

https://pastebin.com/cxZAXsgm

https://pastebin.com/J9J8uBv7

https://pastebin.com/kCLcU73B

https://pastebin.com/kYSKAjgN

```
---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// Ouch. That hurt :(

Time: 8/13/22, 9:35 AM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 13
	at java.base/java.util.Calendar.getDisplayName(Calendar.java:2139)
	at java.base/java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1160)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:1001)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:971)
	at java.base/java.text.DateFormat.format(DateFormat.java:378)
	at net.minecraft.advancements.CriterionProgress.serializeToJson(CriterionProgress.java:45)
	at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(AdvancementProgress.java:230)
	at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(AdvancementProgress.java:224)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at net.minecraft.server.PlayerAdvancements.save(PlayerAdvancements.java:237)
	at net.minecraft.server.players.PlayerList.save(PlayerList.java:599)
	at net.minecraft.server.players.PlayerList.lambda$saveAll$7(PlayerList.java:1289)
	at net.minecraft.server.MCUtil.ensureMain(MCUtil.java:377)
	at net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:1282)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1209)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Purpur version

> version
[15:37:33 INFO]: Checking version, please wait...
[15:37:34 INFO]: Current: git-Purpur-1735 (MC: 1.19)*
Previous: git-Purpur-1713 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

The server crashed five times today. I checked the crash report and found that it was not caused by the plugin. The reason for using 1.19 instead of 1.19.2 is that the plugin I am using does not support 1.19.2

**Comment by ThebestkillerTBK** [comment]
Try to remove plugins half by half
They may indirectly cause the crash

**Comment by BillyGalbreath** [comment]
1) You are _not_ running the latest version of Purpur available from our site.
2) Your version is _not_ supported by Purpur anymore.
3) Offline mode servers are _not_ supported by Purpur.
