### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#1144]
### Spark link

нету

### Stack trace

```
paste your stack trace or a paste.gg link here!
```
Downloading vanilla jar...
Failed to download vanilla jar
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at io.papermc.paperclip.Paperclip.checkVanillaJar(Paperclip.java:191)
        at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:122)
        at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:95)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:49)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 18 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 24 more

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

запускал сервер решил удалить и заного запустить с тем же ядром но вышла ошибка

**Comment by encode42** [comment]
Your version of Minecraft is *not* supported by Purpur.

**Comment by ghost** [comment]
это на всех версиях я уже пробывал так что об этом не волнуйтесь на 1.17.1 тоже такое происходит у меня на пк

**Comment by ghost** [comment]
поэтому нужна помощь

**Comment by Overwrite987** [comment]
> это на всех версиях я уже пробывал так что об этом не волнуйтесь на 1.17.1 тоже такое происходит у меня на пк
english pls
also
try on normal host

**Comment by ghost** [comment]
this error appears on all versions including 1.17.1 i tried it don't worry

**Comment by ghost** [comment]
this is localhost

**Comment by Overwrite987** [comment]
> this is localhost

then try on VPS/Dedi
