### ISSUE TITLE
Incompatibility with Magic plugin

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#115]
RE: https://github.com/elBukkit/MagicPlugin/issues/816

**Describe the bug**
A patch conflict / change to arrow despawn nms seems to break compatibility with the Magic plugin.

**To Reproduce**
* Use latest magic dev build.
* Start Purpur based server and see start-up exception.

**Screenshots or Videos**
```
[19:00:43] [Server thread/INFO]: [Magic] Enabling Magic v8.2-SNAPSHOT-bbde4f4
[19:00:43] [Server thread/WARN]: [Magic] [33m An error occurred, setting arrow lifespan will not work[0m
java.lang.NoSuchFieldException: ar
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_51]
	at com.elmakers.mine.bukkit.utility.NMSUtils.initialize(NMSUtils.java:1516) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Purpur-886]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Purpur-886]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Purpur-886]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Purpur-886]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Purpur-886]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.4.jar:git-Purpur-886]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[patched_1.16.4.jar:git-Purpur-886]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Purpur-886]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Purpur-886]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3052/1768406003.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:00:43] [Server thread/INFO]: [Magic] Using backwards-compatibility layer. It is highly recommended that you update to the latest Spigot version and/or the latest Magic version.[m
```

**Plugins**
Magic dev 3426

**Version**
Purpur dev 886

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No.

**Additional context**
First noticed when experimenting with the Yatopia fork for experimental benchmarking. Issue was claimed to be a Purpur patch conflict due to the field now being in IProjectile for all projectiles instead of in EntityArrow and is outside the scope of that fork to fix.

Magic dev states it is outside the scope of the plugin to fix since compatibility is only guaranteed with Spigot.

Caused by this breaking patch?
https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0121-Despawn-rate-config-options-per-projectile-type.patch

**Comment by jpenilla** [comment]
Plugin issue, see further discussion at https://github.com/elBukkit/MagicPlugin/issues/816

**Comment by NathanWolf** [comment]
Thanks for the help, I didn't mean to cause any of you trouble.

> Magic dev states it is outside the scope of the plugin to fix since compatibility is only guaranteed with Spigot.

This is true, to be clear it is just too difficult to maintain compatibility with forks given all of the NMS I use, it's not anything against Purpur or any particular fork. I've tried to PR most of what I need to Spigot, but as you know some things just won't get accepted or get stuck in the review process.

Plus I have backwards compatibility to worry about, so an API-only version of my plugin is not really in sight.

All regrettable, all excuses, but nonetheless it is what it is.

Anyway, I will put in a fix for this, hopefully that will help future Paper compatibility as well. Thanks again!

**Comment by jpenilla** [comment]
No problem, glad we could get it fixed quickly.
