### ISSUE TITLE
Entity prevented from being added/removed to world

### ISSUE THREAD

**Issue by kaxonomy** [pl3xgaming/Purpur#1212]
### Spark link

https://spark.lucko.me/D0RQrBg9Oa (issue not performance related)

### Expected behavior

Entities are removed when I call the `Entity#remove()` method from the main synchronous thread.

### Observed/Actual behavior

Entities are not being removed, and are instead throwing an error even when the thread is validated with `Bukkit#isPrimaryThread()`:
```
[02:46:56 WARN]: Entity EntityItem['Stone'/185, uuid='d44aece3-1808-46ce-97b6-da017348bded', l='ServerLevel[world]', x=158.50, y=89.32, z=242.30, cpos=[9, 15], tl=0, v=true] is currently prevented from being added/removed to world since it is processing section status updates
java.lang.Throwable: null
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4507) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.world.entity.Entity.remove(Entity.java:706) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.world.entity.Entity.discard(Entity.java:688) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.remove(CraftEntity.java:693) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at tech.kaxon.vlsurvival.limiters.ChunkScanner.onEntityAddToWorld(ChunkScanner.java:262) ~[VLSurvival.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor155.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1857]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2673) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2602) ~[?:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:388) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:326) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1565) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1468) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1463) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2378) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2463) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1939) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1857]
```

### Steps/models to reproduce

Listen to an event such as EntityAddToWorldEvent, try to remove an entity such as an item, then spawn/drop that entity. Example code:
```java
@EventHandler
public void onEntityAddToWorld(EntityAddToWorldEvent event) {
    if (event.getEntityType() == EntityType.DROPPED_ITEM) {
        if (Bukkit.isPrimaryThread()) {
            System.out.println("Dropped item spawned on main thread");
            event.getEntity().remove();
        }
    }
}
```

### Purpur version

Current: git-Purpur-1857 (MC: 1.19.2)*
Previous: git-petal-"cc69154" (MC: 1.19.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by JanTuck** [comment]
Does the issue persist if you schedule a removal a tick after it was added? It doesn’t seem to complain about the thread not being the main thread, but rather you removing it before it finished with its status update.

**Comment by kaxonomy** [comment]
> Does the issue persist if you schedule a removal a tick after it was added? It doesn’t seem to complain about the thread not being the main thread, but rather you removing it before it finished with its status update.

This appears to fix it. Is this still considered a bug since paper doesn't require this behavior?

**Comment by JanTuck** [comment]
> > Does the issue persist if you schedule a removal a tick after it was added? It doesn’t seem to complain about the thread not being the main thread, but rather you removing it before it finished with its status update.
> 
> This appears to fix it. Is this still considered a bug since paper doesn't require this behavior?

You sure this works on paper?

**Comment by kaxonomy** [comment]
> > onsidered a bug since paper doesn't require this behavior?
> 
> You sure this works on paper?

Yes

**Comment by Owen1212055** [comment]
This shouldn't work on paper... see https://github.com/PaperMC/Paper/issues/8490

**Comment by BillyGalbreath** [comment]
It doesn't work on Paper either. We get unchecked claims/lies like that all the time, unfortunately.

**Comment by kaxonomy** [comment]
Thanks, just wanted to add that it used to work on paper prior to the chunk rewrite. Sorry for assumptions that it was still the case.
