### ISSUE TITLE
plugin compability issue

### ISSUE THREAD

**Issue by mcdoeswhat** [pl3xgaming/Purpur#1219]
### Spark link

1

### Stack trace

```
[10:44:15 WARN]: [InteractiveChat] Task #9777 for InteractiveChat v4.2.4.0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_19_R2.block.CraftBlockState incompatible with io.papermc.paper.block.LockableTileState
        at net.minecraft.world.level.block.entity.BaseContainerBlockEntity.canUnlock(BaseContainerBlockEntity.java:85) ~[?:?]
        at net.minecraft.world.level.block.entity.BaseContainerBlockEntity.canOpen(BaseContainerBlockEntity.java:72) ~[?:?]
        at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.canOpen(RandomizableContainerBlockEntity.java:157) ~[?:?]
        at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.createMenu(RandomizableContainerBlockEntity.java:163) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1582) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:338) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at com.loohp.interactivechat.Commands.lambda$onCommand$13(Commands.java:435) ~[InteractiveChat-4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1872]
        at java.lang.Thread.run(Thread.java:889) ~[?:?]
```

### Actions to reproduce (if known)

this error only occurs on the latest version of purpur(git-Purpur-1872),
purpur-1.19.3-1861 has no problem

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Pantera07** [comment]
Can you reproduce with Paper?

**Comment by mcdoeswhat** [comment]
no,paper latest version works fine(paper-1.19.3-341)

**Comment by Pantera07** [comment]
> no,paper latest version works fine(paper-1.19.3-341)

Upstream update is needed to fix this issue.

**Comment by Pantera07** [comment]
Paper recently fixed bugs related to plugins.

https://github.com/PaperMC/Paper/pull/8684
https://github.com/PaperMC/Paper/pull/8687
