### ISSUE TITLE
Sometimes the existence of the Spark plugin is not detected correctly

### ISSUE THREAD

**Issue by ViewShumoon** [pl3xgaming/Purpur#1249]
### Spark link

null

### Expected behavior

At startup, Purpur detects the Spark plugin in the plugins folder and cache folder then use it, skips the download and installation of Spark. The total time consumption should be in 0.5s

### Observed/Actual behavior

Purpur sometimes couldn't detect the existence of spark, whether the plugins folder or the cache folder.
Then tries to download it on its own, and times out, make the startup time of 6 seconds to 126 seconds.

Sometimes it can be detected, but it can take several seconds to detect

### Steps/models to reproduce

1. Download Spark [latest](https://spark.lucko.me/download) or other version support 1.19.3
2. Put it in the plugins folder
3. Start Purpur server
4. Watch the program running to line below.
``` log
Paper: Using Java compression from Velocity.
Paper: Using Java cipher from Velocity.
**(watch this line)**
```
 5. If Purpur detects Spark, stop and run again.

### Purpur version

[21:08:25 INFO]: Checking version, please wait...
[21:08:26 INFO]: Current: git-Purpur-1894 (MC: 1.19.3)*
Previous: git-Purpur-1890 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

- Detected log 1
  ``` log
  [21:12:19] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
  [21:12:22] [Server thread/INFO]: Purpur: Using user-provided spark plugin instead of our own.
  [21:12:22] [Server thread/INFO]: [spark] Loading spark v1.10.26
  ...
  [21:12:23] [Server thread/INFO]: [spark] Enabling spark v1.10.26
  [21:12:24] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
  [21:12:24] [Server thread/INFO]: [spark] Starting background profiler...
  [21:12:25] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
  [21:12:25] [Server thread/INFO]: Running delayed init tasks
  [21:12:25] [Server thread/INFO]: Done (6.707s)! For help, type "help"
  ```

- Not detected log 1  
  ``` log
  [21:12:43 INFO]: Starting Minecraft server on *:25565
  [21:12:43 INFO]: Using default channel type
  [21:12:43 INFO]: Paper: Using Java compression from Velocity.
  [21:12:43 INFO]: Paper: Using Java cipher from Velocity.
  [21:13:04 ERROR]: Purpur: Failed to download and install spark plugin
  [21:13:04 WARN]: java.net.ConnectException: Connection timed out: connect
  [21:13:04 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
  [21:13:04 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
  [21:13:04 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
  [21:13:04 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
  [21:13:04 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
  [21:13:04 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
  [21:13:04 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
  [21:13:04 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
  [21:13:04 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
  [21:13:04 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
  [21:13:04 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)有时能够检测到，但是会花费好几秒的时间检测
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
  [21:13:04 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
  [21:13:04 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
  [21:13:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:462)
  [21:13:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
  [21:13:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
  [21:13:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
  [21:13:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
  [21:13:05 INFO]: [spark] Loading spark v1.10.26
  [21:13:05 INFO]: Server permissions file permissions.yml is empty, ignoring it
  [21:13:05 INFO]: Preparing level "world"
  [21:13:05 INFO]: Preparing start region for dimension minecraft:overworld
  [21:13:06 INFO]: Time elapsed: 152 ms
  [21:13:06 INFO]: Preparing start region for dimension minecraft:the_nether
  [21:13:06 INFO]: Time elapsed: 14 ms
  [21:13:06 INFO]: Preparing start region for dimension minecraft:the_end
  [21:13:06 INFO]: Time elapsed: 10 ms
  [21:13:06 INFO]: [spark] Enabling spark v1.10.26
  [21:13:06 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
  [21:13:07 INFO]: [spark] Starting background profiler...
  [21:13:07 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
  [21:13:07 INFO]: Running delayed init tasks
  [21:13:07 INFO]: Done (24.509s)! For help, type "help"
  ```

- Not detected log 2
``` log
  [20:51:25 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
  [20:51:25 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
  [20:53:37 ERROR]: Purpur: Failed to download and install spark plugin
  [20:53:37 WARN]: java.net.ConnectException: Connection timed out: connect
  [20:53:37 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
  [20:53:37 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
  [20:53:37 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
  [20:53:37 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
  [20:53:37 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
  [20:53:37 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
  [20:53:37 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
  [20:53:37 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
  [20:53:37 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
  [20:53:37 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
  [20:53:37 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
  [20:53:37 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
  [20:53:37 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
  [20:53:37 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:462)
  [20:53:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
  [20:53:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
  [20:53:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
  [20:53:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

  ...
  
  [20:53:46 INFO]: Running delayed init tasks
  [20:53:46 INFO]: Done (141.128s)! For help, type "help"
```

**Comment by FallenCrystal** [comment]
same problem. but purpur has hardly detected Spark.

**Comment by granny** [comment]
I've added a proper timeout to accessing the spark api. It should now take ~5-10 seconds to timeout instead of ~infinity if for whatever reason the server can't open a connection or read the file/SHA1 content.

If you'd like, you can use the `-Purpur.IReallyDontWantSpark` system property flag to avoid our spark download system completely.
