### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Bruce0203** [pl3xgaming/Purpur#1262]
### Spark link

none

### Stack trace

```
[15:01:22] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:60) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:36) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.level.ChunkMap.lambda$playerLoadedChunk$15(ChunkMap.java:1418) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1378) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:828) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:581) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1356) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Actions to reproduce (if known)

chunk load

### Purpur version

(purpur-1.19.2.jar:git-Purpur-1858)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Your version of Minecraft is not supported by Purpur, and a Spark link is required for debugging purposes.

Reproduce this issue on the *latest* version of Purpur, and re-open the issue with the required information if successful.
