### ISSUE TITLE
AFK broadcast color formatting crashes player

### ISSUE THREAD

**Issue by Roan-V** [pl3xgaming/Purpur#1316]
### Spark link

https://spark.lucko.me/pB7iKOMDEi

### Expected behavior

- Using the `afk-tab-list-prefix` and related settings players can be displayed with color formatting in the tablist
- Players marked as AFK lose that color formatting when they come back
- Players don't crash

### Observed/Actual behavior

- Players are marked as AFK, with the correct color formatting
- Players coming back from AFK keep the color formatting in the tablist 
- Players that go AFK for a second time experience a crash

### Steps/models to reproduce

1. Create a new purpur server
2. Set a `player-idle-timeout` in server.properties (I set it to 1 for testing)
3. In purpur.yml:
- Disable `kick-if-idle`
- Enable `update-tab-list`
- Set `afk-tab-list-prefix` to `<gray><italic>` (haven't tried with other color and formatting changes yet)
4. Join the world, and wait for the idle timer to run out
5. Player should correctly be marked as afk, with color formatting in the tablist
6. Move around, `afk-broadcast-back` message will be sent, but player will incorrectly keep color formatting in the tablist
7. Wait for the idle timer to run out again
8. Experience client crash

### Purpur version

[19:37:28 INFO]: Checking version, please wait...
[19:37:28 INFO]: Current: git-Purpur-1964 (MC: 1.19.4)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Server logs: https://mclo.gs/6KNG5Rz

Error snippet from that log:
```
[19:31:02] [Server thread/INFO]: 404_not_found_ is now AFK
[19:31:02] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:59065
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	<gray><italic> 7 o404_not_found_
	              ^^
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:79) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:45) ~[adventure-text-minimessage-4.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:540) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at net.minecraft.server.level.ServerPlayer.setAfk(ServerPlayer.java:2141) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:466) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1605) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1964]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:31:02] [Server thread/INFO]: 404_not_found_ lost connection: Internal server error
[19:31:02] [Server thread/INFO]: 404_not_found_ left the game
```

**Comment by GeorgeV220** [comment]
If you have legacy formatting codes, remove them (for example §7 or &7)

**Comment by Roan-V** [comment]
I don't, see spark link for configs

**Comment by Roan-V** [comment]
I don't, this is a freshly created server to test this issue
**Steps/models to reproduce** has a list of the only changes made to the defaults
See spark link for configs

**Comment by RhythmicSys** [comment]
I can confirm this issue:

## Player going AFK, tab screen changes to the formatted text

<img src="https://github.com/PurpurMC/Purpur/assets/45906780/6905a5e0-41b3-4f3e-871b-86769170edb1" alt="Player going AFK, tab screen shows correct format" width="350" height="200">

## Player leaving AFK, tab screen does not revert to normal text

<img src="https://github.com/PurpurMC/Purpur/assets/45906780/1e78b48c-7ebc-42eb-9abe-1e9e55b3310c" alt="Player leaving AFK, tab screen does not fix format to it's original state" width="350" height="200">

## Player goes AFK again and crashes

<img src="https://github.com/PurpurMC/Purpur/assets/45906780/0e55f655-4ff9-4801-81c9-8460f09616af" alt="Player crash screen which reads 'internal server error'" width="350" height="200">

<details>
<summary> 

## Server Logs </summary>

```
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7-LTS) Host: Linux 5.19.0-41-generic (amd64)
Loading libraries, please wait...
[17:03:04 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:03:05 INFO]: Loaded 7 recipes
[17:03:05 INFO]: Starting minecraft server version 1.19.4
[17:03:05 INFO]: Loading properties
[17:03:05 INFO]: This server is running Purpur version git-Purpur-1970 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 3325421 on HEAD)
[17:03:05 INFO]: Server Ping Player Sample Count: 12
[17:03:05 INFO]: Using 4 threads for Netty based IO
[17:03:06 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[17:03:06 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[17:03:06 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[17:03:06 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[17:03:06 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[17:03:06 INFO]: Default game type: SURVIVAL
[17:03:06 INFO]: Generating keypair
[17:03:06 INFO]: Starting Minecraft server on *:25565
[17:03:06 INFO]: Using epoll channel type
[17:03:06 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[17:03:06 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[17:03:07 INFO]: [spark] Loading server plugin spark v1.10.38
[17:03:07 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:03:07 INFO]: Preparing level "world"
[17:03:07 INFO]: Preparing start region for dimension minecraft:overworld
[17:03:07 INFO]: Time elapsed: 68 ms
[17:03:07 INFO]: Preparing start region for dimension minecraft:the_nether
[17:03:07 INFO]: Time elapsed: 26 ms
[17:03:07 INFO]: Preparing start region for dimension minecraft:the_end
[17:03:07 INFO]: Time elapsed: 23 ms
[17:03:07 INFO]: [spark] Enabling spark v1.10.38
[17:03:08 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[17:03:08 INFO]: [spark] Starting background profiler...
[17:03:08 INFO]: Running delayed init tasks
[17:03:08 INFO]: Done (2.585s)! For help, type "help"
[17:03:14 INFO]: UUID of player DuskOfDarkness is 344f7a7a-beeb-4926-93b5-db81fcfeee1b
[17:03:14 INFO]: DuskOfDarkness joined the game
[17:03:14 INFO]: DuskOfDarkness[/[0:0:0:0:0:0:0:1%0]:51924] logged in with entity id 128 at ([world]12.5, 65.0, -1.5)
[17:05:21 INFO]: DuskOfDarkness is now AFK
[17:05:39 INFO]: DuskOfDarkness is no longer AFK
[17:06:06 INFO]: <DuskOfDarkness> e
[17:08:27 INFO]: DuskOfDarkness is now AFK
[17:08:27 WARN]: Failed to handle packet for /[0:0:0:0:0:0:0:1%0]:51924
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	<gray><italic>[AFK] §7§o[AFK] DuskOfDarkness
	                    ^^
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:79) ~[adventure-text-minimessage-4.13.1.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:45) ~[adventure-text-minimessage-4.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:544) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at net.minecraft.server.level.ServerPlayer.setAfk(ServerPlayer.java:2143) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:467) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:604) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1605) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1970]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:08:27 INFO]: DuskOfDarkness lost connection: Internal server error
[17:08:27 INFO]: DuskOfDarkness left the game
> stop
[17:08:52 INFO]: Stopping the server
[17:08:52 INFO]: Stopping server
[17:08:52 INFO]: [spark] Disabling spark v1.10.38
[17:08:52 INFO]: Saving players
[17:08:52 INFO]: Saving worlds
[17:08:52 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:08:52 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[17:08:52 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[17:08:52 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[17:08:52 INFO]: [ChunkHolderManager] Saved 1603 block chunks, 241 entity chunks, 3 poi chunks in world 'world' in 0.50s
[17:08:52 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:08:52 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[17:08:52 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[17:08:52 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[17:08:52 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[17:08:52 INFO]: [ChunkHolderManager] Saved 6 block chunks, 20 entity chunks, 0 poi chunks in world 'world_nether' in 0.01s
[17:08:52 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:08:52 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[17:08:52 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[17:08:52 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[17:08:52 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[17:08:52 INFO]: [ChunkHolderManager] Saved 10 block chunks, 10 entity chunks, 0 poi chunks in world 'world_the_end' in 0.01s
[17:08:52 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:08:52 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:08:52 INFO]: Flushing Chunk IO
> 2023-05-13 17:08:52,855 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[17:08:52 INFO]: Closing Thread Pool
[17:08:52 INFO]: Closing Server
```
</details>

**Comment by GeorgeV220** [comment]
From what I understand, the problem is that MiniMessage parses text to legacy color codes (§), but when a player goes AFK and then comes back, the server does not remove the color codes. This means that when the player goes AFK again, MiniMessage tries to parse the legacy color codes (§).
