### ISSUE TITLE
java.lang.NullPointerException: Profile name must not be null

### ISSUE THREAD

**Issue by DexterSK** [pl3xgaming/Purpur#1439]
### Spark link

https://spark.lucko.me/3lkcLZdtRr

### Expected behavior

No error / warning

### Observed/Actual behavior

`java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248) ~[purpur-1.20.2.jar:git-Purpur-2064]
        at sk.DexterSK.CoinFlip.common.game.CoinFlipGame.lambda$0(CoinFlipGame.java:54) ~[AdvancedCoinflip-6.7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2064]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2064]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Steps/models to reproduce

Use [setOwningPlayer](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/SkullMeta.html#setOwningPlayer(org.bukkit.OfflinePlayer)) on PLAYER_HEAD ItemStack

### Purpur version

 git-Purpur-2064 (MC: 1.20.2)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

[https://github.com/PaperMC/Paper/pull/9770](https://github.com/PaperMC/Paper/pull/9770)

**Comment by granny** [comment]
Closing since this is an upstream issue, not a Purpur issue.
