### ISSUE TITLE
AnLinux Ubuntu trough Termux crashes

### ISSUE THREAD

**Issue by Simx303** [pl3xgaming/Purpur#1485]
### Spark link

cannot cause server doesnt start

### Stack trace

hs_err : https://paste.gg/p/anonymous/8ac8beccaccc469e96c84cc82ece7a2e/files/25bf851c913941da8282097ff25fc428/raw
log : https://paste.gg/p/anonymous/4fd0f42298cc460996341c4d8acfac06/files/612c5a37cdea4e24b264c94c40e4f300/raw

crash report : 
```
---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// You're mean.

Time: 2024-02-09 13:50:17
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1147)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (aarch64) version 4.14.113-24230781
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 212121200 bytes (202 MiB) / 587202560 bytes (560 MiB) up to 2994733056 bytes (2856 MiB)
	CPUs: 8
	Processor Vendor: null
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x003 Stepping r1p0
	Microarchitecture: ERR
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9585.14
	Virtual memory used (MB): 8096.96
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 873.46
	JVM Flags: 0 total; 
	CraftBukkit Information: 
   Running: Purpur version git-Purpur-2138 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING Timer hack thread: [java.base@17.0.6/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:712)], WAITING RegionFile I/O Thread #0: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING Worker-Main-1: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.base@17.0.6/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], WAITING Worker-Main-2: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.base@17.0.6/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], WAITING Tuinity Chunk System Worker #0: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING JNA Cleaner: [java.base@17.0.6/java.lang.Object.wait(Native Method), java.base@17.0.6/java.lang.ref.ReferenceQueue.remove(Unknown Source), java.base@17.0.6/java.lang.ref.ReferenceQueue.remove(Unknown Source), com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)], WAITING Finalizer: [java.base@17.0.6/java.lang.Object.wait(Native Method), java.base@17.0.6/java.lang.ref.ReferenceQueue.remove(Unknown Source), java.base@17.0.6/java.lang.ref.ReferenceQueue.remove(Unknown Source), java.base@17.0.6/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], RUNNABLE Server console handler: [java.base@17.0.6/java.io.FileInputStream.read0(Native Method), java.base@17.0.6/java.io.FileInputStream.read(Unknown Source), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:103)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-7-thread-1: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], RUNNABLE ServerMain: [io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.generateBFSOrder(RegionizedPlayerChunkLoader.java:346), io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.<clinit>(RegionizedPlayerChunkLoader.java:388), java.base@17.0.6/java.lang.Class.forName0(Native Method), java.base@17.0.6/java.lang.Class.forName(Unknown Source), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:397), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:393), org.bukkit.craftbukkit.Main.main(Main.java:386), java.base@17.0.6/java.lang.invoke.LambdaForm$DMH/0x0000000800c0a000.invokeStatic(LambdaForm$DMH), java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x0000000800c0ac00.invoke(LambdaForm$MH), java.base@17.0.6/java.lang.invoke.LambdaForm$MH/0x0000000800c0a800.invoke_MT(LambdaForm$MH), app//io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42), app//io.papermc.paperclip.Paperclip$$Lambda$9/0x0000000800c01c78.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING Watchdog Thread: [java.base@17.0.6/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:240)], RUNNABLE Reference Handler: [java.base@17.0.6/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.6/java.lang.ref.Reference.processPendingReferences(Unknown Source), java.base@17.0.6/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], RUNNABLE Notification Thread: [], WAITING Tuinity Chunk System Worker #1: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], TIMED_WAITING Keep-Alive-Timer: [java.base@17.0.6/java.lang.Thread.sleep(Native Method), java.base@17.0.6/sun.net.www.http.KeepAliveCache.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source), java.base@17.0.6/jdk.internal.misc.InnocuousThread.run(Unknown Source)], RUNNABLE Server thread: [java.base@17.0.6/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.6/java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_20_R3.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_20_R3.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:62), net.minecraft.CrashReport.<init>(CrashReport.java:40), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1330), net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323), net.minecraft.server.MinecraftServer$$Lambda$6027/0x0000000801738638.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source), java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.base@17.0.6/java.util.concurrent.ArrayBlockingQueue.take(Unknown Source), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:82), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:74)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING process reaper: [java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.base@17.0.6/java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:209), io.netty.channel.epoll.Native.epollWait(Native.java:202), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.6/java.lang.Thread.run(Unknown Source)], TIMED_WAITING Common-Cleaner: [java.base@17.0.6/java.lang.Object.wait(Native Method), java.base@17.0.6/java.lang.ref.ReferenceQueue.remove(Unknown Source), java.base@17.0.6/jdk.internal.ref.CleanerImpl.run(Unknown Source), java.base@17.0.6/java.lang.Thread.run(Unknown Source), java.base@17.0.6/jdk.internal.misc.InnocuousThread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, file/bukkit
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'Purpur'
	Type: Dedicated Server (map_server.txt)
```

## Apps
1. Termux 0.0118 from fdroid
2. AnLinux(exa lab) from play store

## Ubuntu setup
1. Select Ubuntu in AnLinux. Click copy
2. In termux run: pkg upgrade 
3. Then Run copied code in Termux. `./start-ubuntu.sh` to enter ubuntu

## OpenJDK setup
Note: My phone is _Samsung Note 10+_. I checked architecture in ubuntu by running `uname -i`. It showed _aarch64_. I used Adoptium Eclipse Temurin jre for that architype(aarch64) .

After the start-ubuntu command. witch enters ubuntu:

apt update
apt upgrade
1. `wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jre_aarch64_linux_hotspot_17.0.10_7.tar.gz`
2. `tar -xvzf OpenJDK17U-jre_aarch64_linux_hotspot_17.0.10_7.tar.gz -C /opt/jdk`
3. `update-alternatives --install /usr/bin/java java /opt/jdk/jdk-17.0.10+7-jre/bin/java 100`
Check: `java -version`

## Purpur
1. mkdir Server
2. cd Server
3. wget -O purpur.jar https://api.purpurmc.org/v2/purpur/1.20.4/latest/download
Run: java -jar purpur.jar`

### Purpur version

purpur 1.20.4 build 2137 (2138 didnt fix it) 

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

The build 2138 was released the day i downloaded build 2137. Tried it But the error still persists. 

I tried a vanilla 1.15.2 jar and it ran ok. But purpur... it crashes. Then downgraded java to 17.0.6+10. Still purpur crashes. Read in some other issue you can disable spark by adding `-Purpur.IDontWantSpark` to the run command. did not solve the problem.

**Comment by JanTuck** [comment]
I see you're trying on an old outdated vanilla, but i don't see you trying on the latest paper. Is this something you could try?

**Comment by Simx303** [comment]
the phone is not rooted

**Comment by JanTuck** [comment]
Paper is jar just as purpur so just fetch it and run it as you tried to run purpur.

**Comment by Simx303** [comment]
Ok so i downloaded paper #409. And to my surprise it worked!
Done after 13 seconds. Thank you very much.
