### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative

### ISSUE THREAD

**Issue by ZoruaFox** [pl3xgaming/Purpur#1524]
### Spark link

https://spark.lucko.me/muMGPxlUYd

### Stack trace

```java
[23:57:29 ERROR]: Error loading saved data: map_280
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
        at java.base/java.lang.System.arraycopy(Native Method) ~[?:?]
        at java.base/java.io.PushbackInputStream.unread(PushbackInputStream.java:247) ~[?:?]
        at net.minecraft.world.level.storage.DimensionDataStorage.isGzip(DimensionDataStorage.java:122) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.level.storage.DimensionDataStorage.readTagFromDisk(DimensionDataStorage.java:95) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.level.storage.DimensionDataStorage.readSavedData(DimensionDataStorage.java:72) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.level.storage.DimensionDataStorage.get(DimensionDataStorage.java:60) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ServerLevel.getMapData(ServerLevel.java:2207) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.item.MapItem.getSavedData(MapItem.java:55) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:129) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:1174) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1185) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:487) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:895) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1815) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
```

### Actions to reproduce (if known)

1. Starts the server
2. Errors occurred. 

### Purpur version

```java
> version
[00:03:49 INFO]: Checking version, please wait...
[00:03:50 INFO]: Current Purpur Version: 1.20.6-2228-7708a4c (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-2224-be3a6d5 (MC: 1.20.6)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
1. Spark link is expired
2. Are you able to reproduce this on paper? Purpur doesn't touch that area of the code

**Comment by granny** [comment]
This might have been fixed with the most recent Paper upstream.
