### ISSUE TITLE
java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by TymonMarek** [pl3xgaming/Purpur#1541]
### Spark link

https://spark.lucko.me/q9stONjj4s

### Stack trace

[22:54:51 ERROR]: [EntrypointUtil] Failed to open plugin jar plugins/LuckPerms-Bukkit-5.4.134.jar
java.lang.RuntimeException: Failed to open plugin jar plugins/LuckPerms-Bukkit-5.4.134.jar
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:339) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.Main.main(Main.java:128) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at org.bukkit.craftbukkit.Main.main(Main.java:306) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1541) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528) ~[?:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:440) ~[?:?]
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:290) ~[purpur-1.21.jar:1.21-2247-39617d5]
        ... 10 more

### Actions to reproduce (if known)

1. Download latest LuckPerms plugin (https://luckperms.net/download)
2. Place in /plugins
3. Run server
4. Throws error

### Purpur version

> version
[23:02:17 INFO]: Checking version, please wait...
[23:02:18 INFO]: Current Purpur Version: 1.21-2247-39617d5 (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I've also seen this occur with other plugins, like Vault. Unsure if this is a bug upstream with Paper.

**Comment by TymonMarek** [comment]
To add to my original post, I don't think this is a plugin-caused problem, as multiple plugins I have tried to recreate this bug with are facing the same issue, whereas this did not occur on previous versions.

Also, I am pretty certain this is a bug upstream with Paper's PluginRemapper (io.papermc.paper.pluginremap.PluginRemapper)

**Comment by granny** [comment]
That `ZipException: zip END header not found` error usually means that the jar file is corrupted. Try redownloading the plugins and see if the error continues. If it does, then make sure to report this to Paper. It would probably be best to report it in their discord server first, in case it's not an issue with the remapper itself.

**Comment by TymonMarek** [comment]
> That `ZipException: zip END header not found` error usually means that the jar file is corrupted. Try redownloading the plugins and see if the error continues. If it does, then make sure to report this to Paper. It would probably be best to report it in their discord server first, in case it's not an issue with the remapper itself.

I checked MD5 hashes, confirmed jar file of server and plugins, and reinstalled java. Issue still occures.

**Comment by granny** [comment]
Unable to reproduce.

Java Vendor: OpenJDK 21

on the latest Purpur version (build 2251, md5: 0cfb7a9886ee319192698a7ed72fc910, [latest.log](https://mclo.gs/t06O1Pe))

on the latest Paper version (1.21 build 39, sha256: 86e6e7e2ed4fec101ceb265ee6417402516099531e8ef398186f54b3dd460d2e, [latest.log](https://mclo.gs/jMUPoV8))

with LuckPerms bukkit version 5.4.134 (md5: 1e71676ea7629cc64b9e4d1b7deff649)
