### ISSUE TITLE
Bukkit API implementation

### ISSUE THREAD

**Issue by miniking1000** [pl3xgaming/Purpur#1542]
### Spark link

https://spark.lucko.me/xsAIQntPSP

### Expected behavior

to not get an error

### Observed/Actual behavior

this red thing in console:

```
[09:52:16 ERROR]: [CustomizablePlayerModels] Exception while processing cpm packet: cpm_net:set_scl
java.lang.IllegalArgumentException: Invalid UUID string: minecraft:creative_mode_block_range
        at java.base/java.util.UUID.fromString1(UUID.java:282) ~[?:?]
        at java.base/java.util.UUID.fromString(UUID.java:260) ~[?:?]
        at org.bukkit.attribute.AttributeModifier.getUniqueId(AttributeModifier.java:68) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.bukkit.AttributeScaler.lambda$setScale$0(AttributeScaler.java:26) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.bukkit.AttributeScaler.lambda$setScale$1(AttributeScaler.java:26) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305) ~[?:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.bukkit.AttributeScaler.setScale(AttributeScaler.java:23) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.bukkit.AttributeScaler.setScale(AttributeScaler.java:18) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.NetHandler.lambda$addScaler$14(NetHandler.java:539) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.config.PlayerData.rescale(PlayerData.java:140) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.config.PlayerData.rescaleToTarget(PlayerData.java:113) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.packet.SetScaleC2S.handle(SetScaleC2S.java:32) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.IC2SPacket.handle0(IC2SPacket.java:14) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.IC2SPacket.handle(IC2SPacket.java:9) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.IPacket.lambda$handleRaw$0(IPacket.java:13) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.NetHandler.execute(NetHandler.java:415) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.IPacket.handleRaw(IPacket.java:13) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.NetHandler.processPacket(NetHandler.java:199) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.shared.network.NetHandler.receiveServer(NetHandler.java:185) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at CustomPlayerModels-Bukkit-0.6.17b.jar/com.tom.cpm.bukkit.Network.onPluginMessageReceived(Network.java:108) ~[CustomPlayerModels-Bukkit-0.6.17b.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:216) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[purpur-1.21.jar:1.21-2249-1615793]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2249-1615793]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps/models to reproduce

1) join the server with model active or choose model and apply it in the server
2) profit ?

### Purpur version

> version
[09:52:41 INFO]: Checking version, please wait...
[09:52:41 INFO]: Current Purpur Version: 1.21-2249-1615793 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-42119cd (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I know, that this error is caused by CPM plugin, but when I reported this to them I got this as a reply:
`Bukkit API implementation bug, report it to paper/purpur. The bukkit api still uses UUIDs, vanilla changed to resource locations in 1.21.`
so here we are.

**Comment by granny** [comment]
Are you able to reproduce this on Paper or Spigot?

**Comment by miniking1000** [comment]
on spigot everything is fine,
on paper the error is there

**Comment by granny** [comment]
Please send the stacktrace generated while using Paper to their bug tracker: https://github.com/PaperMC/Paper/issues/new/choose

**Comment by granny** [comment]
This is being tracked on Paper's issue tracker here: https://github.com/PaperMC/Paper/issues/11015
