### ISSUE TITLE
Trial spawner interaction issues

### ISSUE THREAD

**Issue by huguyt** [pl3xgaming/Purpur#1546]
### Spark link

https://spark.lucko.me/ovgyXFQRLC

### Expected behavior

Right clicking on the trial_spawner with the spawn egg should change its content.

### Observed/Actual behavior

It doesn't respond.Then the Console output:
[21:21:38 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@20cc556, suppressing error
java.lang.ClassCastException: class org.bukkit.craftbukkit.block.CraftTrialSpawner cannot be cast to class org.bukkit.block.CreatureSpawner (org.bukkit.craftbukkit.block.CraftTrialSpawner and org.bukkit.block.CreatureSpawner are in unnamed module of loader java.net.URLClassLoader @484b61fc)
        at net.minecraft.world.item.SpawnEggItem.useOn(SpawnEggItem.java:80) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:434) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:606) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1949) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1450) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps/models to reproduce

Right click on trial_spawner with any spawn egg

### Purpur version

> version
[21:20:02 INFO]: Current Purpur Version: 1.21-2252-d5c06b4 (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Could reproduce issue, probably some Bukkit/Spigot issue?

**Comment by Onako2** [comment]
Works on Bukkit/Spigot

**Comment by Onako2** [comment]
Works on Paper
