### ISSUE TITLE
MyPet plugin cause NullPointerException error

### ISSUE THREAD

**Issue by andris155** [pl3xgaming/Purpur#156]
**Describe the bug**
MyPet plugin cause NullPointerException error.

**To Reproduce**
Detailed steps to reproduce the behavior.
1. Install the MyPet plugin.
2. Create a MyPet.
3. Give exp to the MyPet and chose the ride skill.
4. Ride on the pet.

**Plugins**
Plugins (108): AdminVedelem, antiRedstoneClock, ArmorStandEditor, BetterGUI, Bridge, BungeeHelpop, BuntetesLogolo, ChatControl, CheckpointAddon, ChestShop, ChestSort, Citizens, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, Duels, DyedBackpacks, EcoPower, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, FarmLimiter, FastAsyncWorldEdit (WorldEdit), FluffyMachines, GPAccruals*, GPTeleport, GriefPrevention, GriefPreventionFlags, GUIHelper, HeadDatabase, HideAndSeek, HolographicDisplays, HonapStaffja, HungerGames, Jatekido, Kemkedes, Kezdes, LibsDisguises, LiteXpansion, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NoCheatPlus, OpenInv, Paintball, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaBot, PomaDrops, PomaExpansion, PotionArmors, ProtocolLib, RabbitsVSPenguins, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SkinsRestorer, sleep-most, Slimefun, SlimefunFix, SlimefunLuckyBlocks, SpleefPlusPlus, StaffChat, StaffTime, SzulinapiKalapok, TAB, TimeIsMoney*, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags

**Version**
This server is running Purpur version git-Purpur-967 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Additional context**
```
[11:39:01 WARN]: java.lang.NullPointerException
[11:39:01 WARN]:        at net.pl3x.purpur.controller.ControllerMoveWASD.tick(ControllerMoveWASD.java:45)
[11:39:01 WARN]:        at net.pl3x.purpur.controller.ControllerMoveWASD.a(ControllerMoveWASD.java:34)
[11:39:01 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1154)
[11:39:01 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.movementTick(EntityMyPet.java:1016)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2520)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:336)
[11:39:01 WARN]:        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.tick(EntityMyPet.java:1338)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1278)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.World.a(World.java:974)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:910)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1435)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1284)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010)
[11:39:01 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176)
[11:39:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by BillyGalbreath** [comment]
Duplicate #64
