### ISSUE TITLE
PEX error

### ISSUE THREAD

**Issue by redbau** [pl3xgaming/Purpur#1598]
### Spark link

https://spark.lucko.me/iFP6NTIolM

### Expected behavior

No console errors for PEX (like when using Paper & Spigot)

### Observed/Actual behavior

[19:26:39] [pool-60-thread-1/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[19:26:39] [pool-60-thread-1/WARN]: 	at PermissionsEx-1.23.4.jar//ru.tehkode.permissions.bukkit.ErrorReport.gistText(ErrorReport.java:120)
[19:26:39] [pool-60-thread-1/WARN]: 	at PermissionsEx-1.23.4.jar//ru.tehkode.permissions.bukkit.ErrorReport$Builder.build(ErrorReport.java:374)
[19:26:39] [pool-60-thread-1/WARN]: 	at PermissionsEx-1.23.4.jar//ru.tehkode.permissions.bukkit.ErrorReport.withException(ErrorReport.java:330)
[19:26:39] [pool-60-thread-1/WARN]: 	at PermissionsEx-1.23.4.jar//ru.tehkode.permissions.bukkit.ErrorReport$2.run(ErrorReport.java:193)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:26:39] [pool-60-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[19:26:39] [pool-60-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/. Full error:
java.lang.NullPointerException

### Steps/models to reproduce

PEX v1.23.4
Every few seconds console throws this error.

### Purpur version

1.21.1-2321-2eaea6a (MC: 1.21.1)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by redbau** [comment]
Forgive me if this is the wrong place, I'm new to Purpur and trying to sort out this new error as I've not seen this before. Thanks!

**Comment by granny** [comment]
Not a Purpur issue, but you can join our discord server for help with your problem in the #help-and-support channel. https://purpurmc.org/discord
