### ISSUE TITLE
Server crash when trying to set a breedable item on polar bears.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#16]
Purpur dev 519

```
Description: Exception in server tick loop

net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:COD
	at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(SourceFile:38)
	at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(SourceFile:43)
	at net.pl3x.purpur.PurpurWorldConfig.polarBearSettings(PurpurWorldConfig.java:700)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.pl3x.purpur.PurpurConfig.readConfig(PurpurConfig.java:90)
	at net.pl3x.purpur.PurpurWorldConfig.init(PurpurWorldConfig.java:37)
	at net.pl3x.purpur.PurpurWorldConfig.<init>(PurpurWorldConfig.java:32)
	at net.minecraft.server.v1_15_R1.World.<init>(World.java:138)
	at net.minecraft.server.v1_15_R1.WorldServer.<init>(WorldServer.java:545)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:405)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:336)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:903)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
```
      polar_bear:
        breedable-item: 'COD'
        ridable: false
        ridable-in-water: false
        require-shift-to-mount: true
```

Tried setting ``breedable-item: COD``, ``breedable-item: 'COD'``, & ``breedable-item: minecraft:COD``. The server crashes immediately after initialization during start-up procedure. Setting it back to default ``breedable-item: ''``, server can start-up fine again.

**Comment by BillyGalbreath** [comment]
All namespaces keys are lowercase only. The error is telling you that, too.

```
net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:COD
```

**Comment by mibby** [comment]
Ah, that was definitely it, thanks! I was going off the reference name that Essentials spat out when checking item material name with /itemdb. It references items as all capitalized so it's what I've typically set by habit in configs.
