### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by Nektoo** [pl3xgaming/Purpur#1607]
### Spark link

https://spark.lucko.me/tSzaxg8mtc

### Expected behavior

It lags at the moment

### Observed/Actual behavior

[12:54:07 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@79bb568e, suppressing error
java.lang.IllegalArgumentException: Bound must be positive
        at net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:19) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.world.entity.Entity$RandomRandomSource.nextInt(Entity.java:235) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.Util.getRandom(Util.java:688) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.world.item.TridentItem.releaseUsing(TridentItem.java:141) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:1048) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4379) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1932) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1619) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1596) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1589) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1540) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1550) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1386) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:342) ~[purpur-1.21.3.jar:1.21.3-2331-e86a1b6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps/models to reproduce

https://spark.lucko.me/tSzaxg8mtc

### Purpur version

Checking version, please wait...
[14:07:00 INFO]: Current Purpur Version: 1.21.3-2331-e86a1b6 (MC: 1.21.3)*
* You are 3 version(s) behind

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
- [x] I ticked all the boxes without actually reading them
Nice job.
Also try on Paper :)
