### ISSUE TITLE
trident error, no animation, no damage and console error

### ISSUE THREAD

**Issue by Nektoo** [pl3xgaming/Purpur#1610]
### Spark link

https://spark.lucko.me/tSzaxg8mtc

### Expected behavior

the trident will deal damage and an animation will play

### Observed/Actual behavior

when using a trident on a dragun there is no animation and damage to entities is not dealt and an error is written to the console

### Steps/models to reproduce

![image](https://github.com/user-attachments/assets/6526fa6f-29ba-44d1-8953-aa951216fedb)
[12:41:36 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@4634dca8, suppressing error
java.lang.IllegalArgumentException: Bound must be positive
        at net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:19) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.world.entity.Entity$RandomRandomSource.nextInt(Entity.java:236) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.Util.getRandom(Util.java:688) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.world.item.TridentItem.releaseUsing(TridentItem.java:141) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:1048) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4402) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1932) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1619) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1596) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1589) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1540) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1550) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1386) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:342) ~[purpur-1.21.3.jar:1.21.3-2340-db09358]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Purpur version

[12:42:48 INFO]: Current Purpur Version: 1.21.3-2340-db09358 (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.3-2337-ca668ab (MC: 1.21.3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Hi! Could you try to reproduce on Paper and one time without any plugins?

Consider joining our Discord!  https://purpurmc.org/discord

Also:
- [x] I ticked all the boxes without actually reading them

**Comment by Onako2** [comment]
Couldn't reproduce in build 2340

**Comment by Nektoo** [comment]
I tried it on a completely clean build, everything is the same

https://github.com/user-attachments/assets/230a9f42-2ea9-4379-90af-af25f83e31c9

**Comment by Onako2** [comment]
Oh, sorry! I was thinking that you meant "dragon"

**Comment by Nektoo** [comment]
I apologize for the video quality, at 0:17 you can see the core version

**Comment by Onako2** [comment]
Could reproduce on Purpur now.
Upstream (Paper) is not affected.
