### ISSUE TITLE
Crashes. Only after migrating to Purpur. On Tuinity all are fine

### ISSUE THREAD

**Issue by NDruce** [pl3xgaming/Purpur#254]
**Describe the bug**

Full-log after server was fully and successfully started:
https://mclo.gs/ZGgi4BJ

Just crash-report:

```
Time: 28.03.21 20:26
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.server.v1_16_R3.NetworkManager.execute(NetworkManager.java:129)
	at com.tuinity.tuinity.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:727)
	at com.tuinity.tuinity.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:484)
	at com.tuinity.tuinity.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:599)
	at com.tuinity.tuinity.chunk.PlayerChunkLoader.tick(PlayerChunkLoader.java:418)
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:949)
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1057)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1554)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:430)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1403)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3060/1101839185.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
Startup server, IDK. There only way to understand problem is to see stacktrace.

**Plugins**
`----------------------------------------------------------`
![image](https://user-images.githubusercontent.com/33526036/112761973-5ed2aa00-9006-11eb-95ad-a450277a34e1.png)
`----------------------------------------------------------`

**Version**
I can't start server, so can't execute /version.
Build is `purpurclip-1.16.5-1048.jar` [9dfc780], downloaded 30 minutes ago.

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No. I was running Tuinity b90 and now updated to b218 and not expecting described bug on it.
```
[20:54:31 INFO]: Checking version, please wait...
[20:54:32 INFO]: This server is running Tuinity version git-Tuinity-"94f025a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1048 (MC: 1.16.5)
```

**Comment by NDruce** [comment]
Maybe you just needed to update Tuinity:

![image](https://user-images.githubusercontent.com/33526036/112762611-3c8e5b80-9009-11eb-8506-8262d2ea1398.png)

**Comment by BillyGalbreath** [comment]
Fixed in build 1049

https://github.com/pl3xgaming/Purpur/commit/8b9b214a6db0cf9b4f012195359e21907bc7aee4
