### ISSUE TITLE
Failed to light chunk in Data-packs

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#284]
**Describe the bug**
I recently downloaded a data pack for a new world generation for Paper 1.16.5, it worked fine, I generated 12,000 chunks in advance so that the players could play comfortably, after that I decided to switch to Purpur and I got errors in chunks, lighting errors. I decided to delete the world to solve this problem, in the process of generating new chunks, my server crashed
for the same lighting error, but nothing like this happened on Paper!

**To Reproduce**
To do this, install this data pack on the server

https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/

Install 12-20 thousand chunks to generate, the error may not appear immediately, but be patient

**Screenshots or Videos**
`[17:12:52 FATAL]: Failed to light chunk [-373, 256] in world 'world'
[17:12:52 FATAL]: Failed to schedule load callback for chunk [-373, 256]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R3.ReportedException: Feature placement
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.e(ThreadedMailbox.java:91) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.a(ThreadedMailbox.java:138) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ThreadedMailbox.run(ThreadedMailbox.java:103) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: net.minecraft.server.v1_16_R3.ReportedException: Feature placement
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$36(PlayerChunkMap.java:1403) ~[patched_1.16.5.jar:git-Purpur-1053]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$38(PlayerChunkMap.java:1388) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
... 8 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -380 256
at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:134) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.IWorldReader.getChunkAt(IWorldReader.java:113) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:106) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.getType(RegionLimitedWorldAccess.java:166) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureNetherrackReplaceBlobs.a(SourceFile:38) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureNetherrackReplaceBlobs.generate(SourceFile:16) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureRandom2Configuration.a(SourceFile:20) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureRandom2Configuration.generate(SourceFile:11) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.BiomeBase.a(BiomeBase.java:322) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ChunkGenerator.addDecorations(ChunkGenerator.java:224) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ChunkStatus.lambda$static$9(ChunkStatus.java:82) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.ChunkStatus.a(ChunkStatus.java:204) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$36(PlayerChunkMap.java:1390) ~[patched_1.16.5.jar:git-Purpur-1053]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-1053]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$38(PlayerChunkMap.java:1388) ~[patched_1.16.5.jar:git-Purpur-1053]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
... 8 more`

**Plugins**
Chunky

**Version**
This server is running Purpur version git-Purpur-1053 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No

**Additional context**
I assume the error is due to LightEngine

**Comment by BillyGalbreath** [comment]
Purpur doesnt mess with the light engine or chunk generation. Try to recreate this on Tuinity or Airplane and report to the one where the issue happens.

**Comment by BillyGalbreath** [comment]
Closing. I'm assuming you found out this was a Tuinity bug since you reported it to them https://github.com/Spottedleaf/Tuinity/issues/287
