### ISSUE TITLE
[Server Crash] Exception ticking world

### ISSUE THREAD

**Issue by PierlucaDP** [pl3xgaming/Purpur#326]
**Describe the bug**
The server stops and crashes randomly for Exception ticking world

**Version**
Purpur version git-Purpur-606 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/10/21 6:11 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2003)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.g(PlayerChunkMap.java:2019)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1113)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:919)
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:876)
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1411)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:469)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1263)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:987)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2003)
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.g(PlayerChunkMap.java:2019)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1113)
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:919)
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:876)

-- Affected level --
Details:
	All players: 32 total; ...
	Chunk stats: ServerChunkCache: 7496
	Level dimension: minecraft:cheironcity
	Level name: CheironCity
	Level seed: 8462469037009418021
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (25,73,-184), Chunk: (at 9,4,8 in 1,-12; contains blocks 16,0,-192 to 31,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 135797430 game time, 18462440 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 133310 (now: false), thunder time: 10278 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1411)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:469)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1263)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:987)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-142-generic
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1506495096 bytes (1436 MB) / 4110417920 bytes (3920 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 16
	JVM Flags: 20 total; -Xms1024M -Xmx16384M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	CraftBukkit Information: 
   Running: Purpur version git-Purpur-606 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) false
   Plugins: {...}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { ... }
   
   Force Loaded Chunks: { Tutorial: {}, Phidelya: {}, CheironCity: {},}
	Player Count: 46 ...
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Purpur'
	Type: Dedicated Server (map_server.txt)
```

**Comment by jpenilla** [comment]
1.15.2 is no longer a supported version.
