### ISSUE TITLE
Console spam errors

### ISSUE THREAD

**Issue by mcdoeswhat** [pl3xgaming/Purpur#343]
[09:50:02 WARN]: java.util.NoSuchElementException: No value present
[09:50:02 WARN]:        at java.base/java.util.Optional.get(Optional.java:148)
[09:50:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[09:50:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:50:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1500)
[09:50:02 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:434)
[09:50:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1413)
[09:50:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[09:50:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[09:50:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by YouHaveTrouble** [comment]
Post full log
