### ISSUE TITLE
Libs Disguises self view disguises not working on purpur

### ISSUE THREAD

**Issue by PhanaticD** [pl3xgaming/Purpur#4]
disguises from LibsDisguises do not work on purpur, however when I tested with paper there was no problem

this is the relevant lines: 

https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/utilities/DisguiseUtilities.java#L1554
```
[14:47:57 INFO]: PhanaticD issued server command: /d cow
[14:47:57 WARN]: java.lang.NullPointerException
[14:47:57 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1554)
[14:47:57 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1727)
[14:47:57 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:836)
[14:47:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:47:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[14:47:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1178)
[14:47:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:426)
[14:47:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1105)
[14:47:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:932)
[14:47:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/utilities/DisguiseUtilities.java#L1263
```
[14:47:59 INFO]: PhanaticD issued server command: /u
[14:47:59 WARN]: java.lang.NullPointerException
[14:47:59 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:1263)
[14:47:59 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:539)
[14:47:59 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:480)
[14:47:59 WARN]:        at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:408)
[14:47:59 WARN]:        at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[14:47:59 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:47:59 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[14:47:59 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:740)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1864)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1672)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1036)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1029)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1013)
[14:47:59 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:936)
[14:47:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PhanaticD** [comment]
its gotta be another plugin, I dont get the error with just protocollib and no other plugins
