### ISSUE TITLE
java.lang.NoSuchMethodError: 'void net.minecraft.network.PacketDecompressor.<init>(int, boolean)'

### ISSUE THREAD

**Issue by danirod12** [pl3xgaming/Purpur#561]
### Expected behavior

```
[19:31:07 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper$$Lambda$7528/0x0000000802488000.operationComplete()
java.lang.NoSuchMethodError: 'void net.minecraft.network.PacketDecompressor.<init>(int, boolean)'
        at protocolsupport.zplatform.impl.spigot.network.pipeline.SpigotPacketDecompressor.<init>(SpigotPacketDecompressor.java:22) ~[ProtocolSupport.jar:?]
        at protocolsupport.zplatform.impl.spigot.SpigotMiscUtils.enableCompression(SpigotMiscUtils.java:339) ~[ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener.lambda$finishLogin$11(AbstractLoginListener.java:271) ~[ProtocolSupport.jar:?]
        at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper.lambda$sendPacketBlocking$2(SpigotNetworkManagerWrapper.java:119) ~[ProtocolSupport.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.network.Connection.a(Connection.java:453) ~[app:?]
        at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:424) ~[app:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1320]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Exception become with git-Purpur-1306 -> git-Purpur-1307 update

### Observed/Actual behavior

On git-Purpur-1306 (MC: 1.17.1) works fine, without exception

### Steps/models to reproduce

Join server with installed ProtocolSupport using BungeeCord proxy, idk
On git-Purpur-1307 (MC: 1.17.1) exception appears

### Purpur version

git-Purpur-1320 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
1307 is *not* the latest build (currently #1320) of Purpur. If it continues on latest, bring it up with the ProtocolSupport devs.

**Comment by danirod12** [comment]
I am running the latest version. Try to read exception `~[patched_1.17.1.jar:git-Purpur-1320]`

**Comment by danirod12** [comment]
And also it is a system class `net.minecraft.network.PacketDecompressor` not by ProtocolSupport
And exception become with updating from git-Purpur-1306 to git-Purpur-1307 as i said

**Comment by granny** [comment]
> I am running the latest version. Try to read exception `~[patched_1.17.1.jar:git-Purpur-1320]`

I misread, my bad.

> And also it is a system class `net.minecraft.network.PacketDecompressor` not by ProtocolSupport
> And exception become with updating from git-Purpur-1306 to git-Purpur-1307 as i said

That system class is being used by ProtocolSupport and it’s supposedly missing, yes. 

Build 1307 was an upstream merge, so check to see if you can reproduce this issue using Paper or Tuinity. If you can, then open a ticket in their respective github page.

**Comment by danirod12** [comment]
Checked on `git-Paper-165 (MC: 1.17.1)` (latest), exception not appears

**Comment by danirod12** [comment]
On Tuinity it appears, i will create ticket in Tuinity github, thanks for help
