### ISSUE TITLE
Relatively frequent server crashes

### ISSUE THREAD

**Issue by radiant-ai** [pl3xgaming/Purpur#581]
### Timings link

none

### Stack trace

```
---- Minecraft Crash Report ----
// Sorry :(

Time: 8/11/21, 11:12 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.google.common.collect.Iterators$1.next(Iterators.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at app//net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$updateChunkStatus$6(PersistentEntitySectionManager.java:243)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at java.base/java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2002)
	at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:763)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at app//net.minecraft.world.level.entity.PersistentEntitySectionManager.updateChunkStatus(PersistentEntitySectionManager.java:228)
	at app//net.minecraft.world.level.entity.PersistentEntitySectionManager.updateChunkStatus(PersistentEntitySectionManager.java:214)
	at app//net.minecraft.server.level.ChunkTracker.onFullChunkStatusChange(ChunkTracker.java:2297)
	at app//net.minecraft.server.level.ChunkHolder.demoteFullChunk(ChunkHolder.java:635)
	at app//net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:829)
	at app//net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:215)
	at app//net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:848)
	at app//net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932)
	at app//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:758)
	at app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629)
	at app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492)
	at app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270)
	at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### Actions to reproduce (if known)

There is no way to reproduce this. The crash happens once or twice a day.

### Purpur version

Reported at:
`git-Purpur-1327 (MC: 1.17.1)`

Started happening at:
`git-Purpur-1310 (MC: 1.17.1)`

Never happened at:
`git-Purpur-1301 (MC: 1.17.1)`

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Should this better be reported to Tuinity?

**Comment by BillyGalbreath** [comment]
```
java.util.ConcurrentModificationException
```
You have a plugin that is modifying entities off the main thread
