### ISSUE TITLE
Error executing task on Server java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by l3unnyAnoF4** [pl3xgaming/Purpur#639]
### Expected behavior

```
[04:08:28 FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:461) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1306) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.server.players.UserCache.save(UserCache.java:300) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.players.UserCache.a(UserCache.java:138) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.world.level.block.entity.TileEntitySkull.lambda$updateGameprofile$1(TileEntitySkull.java:162) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1543) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1370]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1370]
```

### Observed/Actual behavior

-

### Steps/models to reproduce

-

### Purpur version

git-Purpur-1370

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Plugins (74): AdvancedEnchantments, antiRedstoneClock, AntiSeedCracker, AsyncWorldEdit, AuctionHouse, AuthMe, BanItem, BlockLocker, BlockParticles, BossShopPro, ChestShop, ChestSort, Chunky, Citizens, CMI, CMIEInjector*, CMILib, CoreProtect, Cosmin, CrateReloaded, CubCustomDrops, CurseOfVanishing, CustomCrafting, DiscordSRV, DivineDrop, eZProtector, FancyBags, FarmControl, FarmingUpgrade, GSit, HeadDatabase, IllegalStack, Images, InventoryKeeper, InventoryRollback-Continued, ItemEdit, ItemShops*, ItemTag, KixsChatGames, LastLoginAPI, LeaderHeadsRevamped, LibsDisguises, LimitedUses*, Logger, LuckPerms, Marriage, MMOItems, MobFarmManager, Multiverse-Core, MythicLib, NashornPlus, Parties, PermissionPortals, PL-Hide-Pro, PlaceholderAPI, PlayerPoints, ProtectionStones, ProtocolLib, PvPLevels, RacesOfThana, SafeDrop*, SaveableItems, ServerSigns, Shopkeepers, TAB, TimedItem, UltimateTimber, Vault, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, XLTournaments, XPBoost

**Comment by l3unnyAnoF4** [comment]
Use Java graalvm-ce-java16-21.2.0

**Comment by BillyGalbreath** [comment]
1) We dont support graalvm. Use hotspot instead.
2) This would be something upstream, as we dont touch anything anywhere near the code that's in that stack. Tuinity does, though, which is now part of Paper. Try recreating the issue on Paper, then report it to them.
