### ISSUE TITLE
Exception while riding an entity using MyPet plugin

### ISSUE THREAD

**Issue by Wirlie** [pl3xgaming/Purpur#64]
**Describe the bug**
I am using the plugin MyPet (https://www.spigotmc.org/resources/mypet-legacy.12725/), and when I ride an entity this exception is displayed at console:
```
[18:25:07 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R2.EntityHuman.getForward()" because "rider" is null
[18:25:07 WARN]:        at net.pl3x.purpur.controller.ControllerMoveWASD.tick(ControllerMoveWASD.java:45)
[18:25:07 WARN]:        at net.pl3x.purpur.controller.ControllerMoveWASD.a(ControllerMoveWASD.java:34)
[18:25:07 WARN]:        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1154)
[18:25:07 WARN]:        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityMyPet.movementTick(EntityMyPet.java:1016)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2503)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:332)
[18:25:07 WARN]:        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityMyPet.tick(EntityMyPet.java:1338)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:1312)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:900)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:966)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006)
[18:25:07 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[18:25:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```

**To Reproduce**
1. Make a server using 1.16.3
2. Put MyPet inside the plugins folder
3. Buy a Baby Wither trough the command /petshop
4. Summon the pet with /petswitch
5. Use /petcst and select the Ride option
6. Put a lead in your hand and right click the pet to ride the pet
7. You will see the exception at console

**Plugins**
[18:39:33 INFO]: Plugins (16): DeluxeChat, Essentials, EssentialsSpawn, LuckPerms, Multiverse-Core, MyPet, PlaceholderAPI, PlugMan, SkinsRestorer, TAB, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit

**Version**
[18:39:55 INFO]: This server is running Purpur version git-Purpur-760 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
I have tested only on PaperMC and the bug is not present, /version output:
[18:42:13 INFO]: This server is running Paper version git-Paper-197 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by BillyGalbreath** [comment]
MyPet plugin is ticking the WASD controller when there is no rider.

Plugin at fault
