### ISSUE TITLE
Warning/Error logspam on login

### ISSUE THREAD

**Issue by Apprisco** [pl3xgaming/Purpur#654]
### Expected behavior

Clean logins, lol

### Observed/Actual behavior

Exception loading entity: 
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.load(Entity.java:2345) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.world.entity.EntityTypes.lambda$create$2(EntityTypes.java:563) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.SystemUtils.a(SystemUtils.java:397) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.world.entity.EntityTypes.a(EntityTypes.java:560) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.world.entity.EntityTypes.b(EntityTypes.java:651) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.world.entity.EntityTypes.a(EntityTypes.java:594) ~[patched_1.17.1.jar:git-Purpur-1383]
        at net.minecraft.world.entity.EntityTypes$1.lambda$tryAdvance$1(EntityTypes.java:618) ~[patched_1.17.1.jar:git-Purpur-1383]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:?]
        at net.minecraft.world.entity.EntityTypes$1.tryAdvance(EntityTypes.java:617) ~[patched_1.17.1.jar:git-Purpur-1383]
        at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$loadEntities$0(EntityStorage.java:72) ~[patched_1.17.1.jar:git-Purpur-1383]
        ... 2 more

### Steps/models to reproduce

Get latest purpur, log in.
[06:44:00 INFO]: Plugins (29): AdvancedPortals, AutomatedCrafting, BKCommonLib, BlockPlacersAndBreakers, Citizens, Enchantssquared, FastAsyncWorldEdit (WorldEdit), GSit, JukeLooper, KeepChunks, LightCleaner, LockProxy, LuckPerms, NBTAPI, NoTotemHand*, PlugMan, ProtocolLib, RHLeafDecay, Sentinel, SimplePortals, SimpleStack, spark, SurvivalInvisiframes, VanillaTweaks, ViaBackwards, ViaRewind, ViaVersion, voicechat, WorldGuard

Plugins seem to make no difference, however.

### Purpur version

This server is running Purpur version git-Purpur-1383 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6856a5d on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

This is most likely one of your plugins corrupting the NBT in your player.dat file(s). Removing plugins _after_ the corruption has occurred will not fix the problem. Most likely culprit is whatever is using that NBTAPI plugin.
