### ISSUE TITLE
I get an error when starting a server with CitizensCMD installed.

### ISSUE THREAD

**Issue by JPlayer3** [pl3xgaming/Purpur#761]
### Expected behavior

There is a plugin that gives an error on startup in Purpur.
PaperMC did not give me any error.

PaperMC version: git-Paper-388 (MC: 1.17.1)
Purpur version: git-Purpur-1428 (MC: 1.17.1)

### Observed/Actual behavior

```
[Server thread/INFO]: [CitizensCMD] Enabling CitizensCMD v2.5.1
[Server thread/ERROR]: Error occurred while enabling CitizensCMD v2.5.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.simpleyaml.configuration.file.YamlFile.saveWithComments()'
	at me.mattstudios.citizenscmd.utility.YamlUtils.copyDefaults(YamlUtils.java:43) ~[CitizensCMD.jar:?]
	at me.mattstudios.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:88) ~[CitizensCMD.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur_patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[Server thread/INFO]: [CitizensCMD] Disabling CitizensCMD v2.5.1
```

### Steps/models to reproduce

All you have to do is install CitizensCMD and run it on PaperMC and Purpur respectively.

### Purpur version

git-Purpur-1428 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other
Is it possible that java_options is the cause?

Because of the garbled characters, I am using the following as fixed
I picked up JAVA_OPTIONS: -Dsun.stdout.encoding=UTF-8 -Dsun.err.encoding=UTF-8 -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

_No response_

**Comment by Oharass** [comment]
Citizenscmd must relocate simpleyaml

**Comment by encode42** [comment]
This should no longer be an issue with the 1.18.X builds. The above is true, that the author of CitizensCMD must relocate their Simple-YAML dependency for >1.18 builds.

**Comment by Fredthedoggy** [comment]
CitizensCMD is deprecated in favor of citizen's built in command system.

https://www.spigotmc.org/resources/citizens-cmd-abandoned.30224/
