### ISSUE TITLE
 Failed to schedule load callback for chunk

### ISSUE THREAD

**Issue by TheWylot** [pl3xgaming/Purpur#821]
### Expected behavior

my server crash for that unknown things

### Observed/Actual behavior

when a person joins in a chunk, the server start crash with a massive log

### Steps/models to reproduce

[09:00:02] [Worker-Main-5/FATAL]: Failed to schedule load callback for chunk [7, 134217727]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R3.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ThreadedMailbox.e(ThreadedMailbox.java:91) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ThreadedMailbox.a(ThreadedMailbox.java:138) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ThreadedMailbox.run(ThreadedMailbox.java:103) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: net.minecraft.server.v1_16_R3.ReportedException: Feature placement
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$36(PlayerChunkMap.java:1362) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$38(PlayerChunkMap.java:1347) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 8 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 6 -134217728
	at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:134) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IWorldReader.getChunkAt(IWorldReader.java:113) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.getChunkAt(RegionLimitedWorldAccess.java:106) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.RegionLimitedWorldAccess.a(RegionLimitedWorldAccess.java:382) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenMinable.a(SourceFile:45) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenMinable.generate(SourceFile:16) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.a(SourceFile:22) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureComposite.generate(SourceFile:14) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldGenFeatureConfigured.a(SourceFile:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.BiomeBase.a(BiomeBase.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkGenerator.addDecorations(ChunkGenerator.java:224) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkStatus.lambda$static$9(ChunkStatus.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkStatus.a(ChunkStatus.java:204) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$36(PlayerChunkMap.java:1349) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$b$38(PlayerChunkMap.java:1347) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 8 more

### Purpur version

[18:58:15 INFO]: Checking version, please wait...
[18:58:15 INFO]: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[18:58:15 INFO]: You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
1.16.5 is unsupported...

**Comment by TheWylot** [comment]
really ?
