### ISSUE TITLE
Kicking Player because of loading Chunks

### ISSUE THREAD

**Issue by JanMartenT** [pl3xgaming/Purpur#857]
### Timings link

https://timings.aikar.co/?id=9071ead8d85841ceb1b1da91d52600f5

### Stack trace

```
[14:22:48 INFO]: UUID of player SharpShoot3r is d0718a75-4d66-4e92-b31f-f47914f143b4
[14:22:48 INFO]: SharpShoot3r joined the game
[14:22:48 WARN]: Failed to handle packet for /94.31.82.185:60194
java.lang.IllegalStateException: Use of an uninitialized palette
        at net.minecraft.world.level.chunk.SingleValuePalette.getSerializedSize(SingleValuePalette.java:71) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.world.level.chunk.PalettedContainer$Data.getSerializedSize(PalettedContainer.java:381) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer.getSerializedSize(PalettedContainer.java:324) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunkSection.getSerializedSize(LevelChunkSection.java:193) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.calculateChunkSize(ClientboundLevelChunkPacketData.java:103) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:48) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:36) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.level.ChunkMap.lambda$playerLoadedChunk$66(ChunkMap.java:2140) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:2139) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:1587) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.level.ChunkMap.updatePlayerStatus(ChunkMap.java:1853) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:2000) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:397) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:323) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:535) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1664) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1522]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:22:48 INFO]: SharpShoot3r lost connection: Internal server error
[14:22:48 INFO]: SharpShoot3r left the game
```

### Actions to reproduce (if known)

It happens, if I fly through the world. I get kicket and can´t join anymore (ame error if I try to login). 
To solve it temporary I have to teleport myself back to the spawn per console, but if I fly again arround and loading new chunks it happens after a very short time again.

### Purpur version

Purpur 1.18.1-R0.1-SNAPSHOT

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
This seems like a plugin issue. Try reproducing without any plugins installed.
