### ISSUE TITLE
pathfinder goal conflict with Paper API

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#86]
**Describe the bug**
I found a bug in Purpur that breaks Paper API
doing:
```java
        Mob e = (Mob) entity;
        Bukkit.getMobGoals().removeAllGoals(e);
```
causes:
```
java.lang.RuntimeException: Can't figure out applicable entity for mob goal class net.pl3x.purpur.pathfinder.PathfinderGoalHasRider
```

it works perfectly on pure paper 1.16.3, only breaks on purpur

**To Reproduce**
use
        Mob e = (Mob) entity;
        Bukkit.getMobGoals().removeAllGoals(e);
and it'll error in console.

**Screenshots or Videos**
None

**Plugins**
Skript, SkStuff

**Version**
This server is running Purpur version git-Purpur-804 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Bug is not present on Paper ( This server is running Paper version git-Paper-195 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT))

**Additional context**
Add any other context about the problem here you think will help resolve the problem.

**Comment by BillyGalbreath** [comment]
Simple plugin to reproduce the error

```java
public class TestPlugin extends JavaPlugin {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new Listener() {
            @EventHandler
            public void onCreatureSpawn(CreatureSpawnEvent event) {
                if (event.getEntityType() == EntityType.RABBIT) {
                    Rabbit rabbit = (Rabbit) event.getEntity();
                    getServer().getMobGoals().removeAllGoals(rabbit);
                }
            }
        }, this);
    }
}
```

Use the vanilla summon command to then spawn a rabbit and get the following error

```
[15:08:06 INFO]: BillyGalbreath issued server command: /summon rabbit
[15:08:06 ERROR]: Could not pass event CreatureSpawnEvent to TestPlugin v1.0-SNAPSHOT
java.lang.RuntimeException: Can't figure out applicable entity for mob goal class net.pl3x.purpur.pathfinder.PathfinderGoalHasRider
	at com.destroystokyo.paper.entity.ai.MobGoalHelper.lambda$getEntity$0(MobGoalHelper.java:349) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1225) ~[?:?]
	at com.destroystokyo.paper.entity.ai.MobGoalHelper.getEntity(MobGoalHelper.java:337) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.destroystokyo.paper.entity.ai.MobGoalHelper.getKey(MobGoalHelper.java:332) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.destroystokyo.paper.entity.ai.PaperVanillaGoal.<init>(PaperVanillaGoal.java:21) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1225) ~[?:?]
	at com.destroystokyo.paper.entity.ai.PaperMobGoals.getAllGoals(PaperMobGoals.java:128) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.destroystokyo.paper.entity.ai.PaperMobGoals.removeAllGoals(PaperMobGoals.java:62) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.destroystokyo.paper.entity.ai.PaperMobGoals.removeAllGoals(PaperMobGoals.java:56) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.pl3x.bukkit.test.TestPlugin$1.onCreatureSpawn(TestPlugin.java:20) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:685) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:606) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.WorldServer.addEntity0(WorldServer.java:1668) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.WorldServer.addEntity(WorldServer.java:1569) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:13) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at net.minecraft.server.v1_16_R2.WorldAccess.addAllEntities(WorldAccess.java:13) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.WorldServer.addAllEntitiesSafely(WorldServer.java:1755) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.WorldServer.addAllEntitiesSafely(WorldServer.java:1745) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.CommandSummon.a(SourceFile:77) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.CommandSummon.c(SourceFile:42) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.CommandDispatcher.a(CommandDispatcher.java:183) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1974) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1777) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[purpur-1.16.3.jar:git-Purpur-"723706d"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[15:08:06 INFO]: [BillyGalbreath: Summoned new Rabbit]
```

**Comment by BillyGalbreath** [comment]
Ok, so the issue here is Paper's API was built with the assumption that all PathfinderGoals are in the NMS package (net.minecraft.server). My ridables pathfinders are in purpur's package. So the API doesnt know these pathfinders exist, and when the implementation runs into them you get the lovely error in my previous comment.

I'll fix this by moving my pathfinder into the NMS package. This will also fix compatibility with any plugins that make the same assumption.
