### ISSUE TITLE
NPE in Bukkit.broadcastMessage(String)

### ISSUE THREAD

**Issue by saharNooby** [pl3xgaming/Purpur#873]
### Expected behavior

No NPE in `Bukkit.broadcaseMessage(String)`.

### Observed/Actual behavior

NPE in `Bukkit.broadcaseMessage(String)`.

After first NPE in `GameManager.java:266`, every call to `Bukkit.broadcaseMessage(String)` was generating NPE in this line of our code and all other places.

```
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2143) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:215) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:189) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcast(CraftServer.java:1597) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcast(CraftServer.java:1569) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcastMessage(CraftServer.java:600) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:308) ~[patched_1.16.5.jar:git-Purpur-1171]
	at me.saharnooby.plugins.<redacted>.GameManager.broadcastLobbyCountdown(GameManager.java:266) ~[?:?]
	at me.saharnooby.plugins.<redacted>.GameManager.lambda$checkCountdown$5(GameManager.java:258) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps/models to reproduce

It is unknown how to reproduce the issue -- it randomly appeared after 8 hours of spigot running. No reloads.

### Purpur version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Paper-792 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Passed message is never null since it is obtained by string concat.

No NPEs on vanilla Paper -- running 24/7 for 3 months until Purpur was installed.

We are now moving from Purpur to vanilla Paper, so we will not attempt to try to reproduce it again.

**Comment by YouHaveTrouble** [comment]
If you're wondering why this got closed, you checked `I am running the latest version of Purpur available from https://purpurmc.org/downloads.` box and your logs clearly show 1.16.5 :)

**Comment by saharNooby** [comment]
>Keep in mind that if you download these builds, you will not receive support.

Fair enough, did not notice the disclaimer on the site.
