### ISSUE TITLE
Error that is spamming on my console 

### ISSUE THREAD

**Issue by JoshuaPHYT** [pl3xgaming/Purpur#889]
### Timings link

https://timings.aikar.co/?id=2f64a4c6dcd249dca3ae390528e6f562

### Expected behavior

no errors that is spamming on my console

### Observed/Actual behavior

Error that is spamming on my console sometimes

### Steps/models to reproduce

[00:57:07 FATAL]: Uncaught exception in thread Profile Lookup Executor #1062
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.2.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[purpur-1.18.1.jar:git-Purpur-1544]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[purpur-1.18.1.jar:git-Purpur-1544]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:155) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:444) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:152) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Purpur version

[01:13:29 INFO]: Checking version, please wait...
[01:13:30 INFO]: Current: git-Purpur-1544 (MC: 1.18.1)*
[01:13:30 INFO]: Previous: git-Purpur-1537 (MC: 1.18.1)
[01:13:30 INFO]: * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
It's pretty self explanetory.

```
[00:57:07 FATAL]: Uncaught exception in thread Profile Lookup Executor #1062
java.lang.IllegalArgumentException: Name and ID cannot both be blank
```

You have a game profile that is missing both the Name and ID.

```
at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:155) ~[?:?]
```

That line tells me it's a player head in your world. Find it and delete it.

**Comment by BillyGalbreath** [comment]
Found out from many reports all over the place today about this bug. Turns out Mojang changed some API stuff that broke Floodgate/Geyser. You need to get the latest update from them for the fix ;)

![image](https://user-images.githubusercontent.com/332527/152275297-725eb4c6-c689-443c-b1cd-8337421c9b81.png)

**Comment by Camotoy** [comment]
Just for reference, because this particular stack trace is from a player head, I don't believe it's caused by Geyser/Floodgate (though perhaps indirectly if a plugin uses a player head of a Bedrock player), but the cause of the stack trace is the same change that affected Floodgate.
