### ISSUE TITLE
Corrupted region file, help identify possible cause

### ISSUE THREAD

**Issue by radiant-ai** [pl3xgaming/Purpur#91]
**Describe the bug**

```
[Paper RegionFile IO Thread/ERROR]: Chunk [-24, -10] header is truncated: expected 0 but read 0
[Paper RegionFile IO Thread/WARN]: Corrupt regionfile header detected! Attempting to re-calculate header offsets for regionfile /home/minecraft/survival/./world/region/r.-1.-1.mca
java.lang.Throwable: null
	at net.minecraft.server.v1_16_R3.RegionFile.recalculateHeader(RegionFile.java:121) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.RegionFile.a(RegionFile.java:589) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.RegionFileCache.readFromRegionFile(RegionFileCache.java:187) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.RegionFileCache.read(RegionFileCache.java:180) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.read(PlayerChunkMap.java:1690) ~[patched_1.16.4.jar:git-Purpur-828]
	at net.minecraft.server.v1_16_R3.WorldServer$2.readData(WorldServer.java:157) ~[patched_1.16.4.jar:git-Purpur-828]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.4.jar:git-Purpur-828]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.4.jar:git-Purpur-828]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.4.jar:git-Purpur-828]
[Paper RegionFile IO Thread/WARN]: Backing up regionfile "/home/minecraft/survival/./world/region/r.-1.-1.mca" to /home/minecraft/survival/./world/region/r.-1.-1.mca.-5074753328597328036.backup
[Paper RegionFile IO Thread/WARN]: Backed up the regionfile to /home/minecraft/survival/./world/region/r.-1.-1.mca.-5074753328597328036.backup
[Paper RegionFile IO Thread/INFO]: Starting summary of changes for regionfile /home/minecraft/survival/./world/region/r.-1.-1.mca
[Paper RegionFile IO Thread/INFO]: Local chunk (8,22) changed to point to newer data or correct chunk in regionfile /home/minecraft/survival/./world/region/r.-1.-1.mca
[Paper RegionFile IO Thread/INFO]: End of change summary for regionfile /home/minecraft/survival/./world/region/r.-1.-1.mca
[Paper RegionFile IO Thread/INFO]: Successfully wrote new header to disk for regionfile /home/minecraft/survival/./world/region/r.-1.-1.mca
```

**To Reproduce**
Don't know, updated to the latest Purpur build.

**Plugins**
```
Plugins (36): AntiAFKPlus, AntiVPN, AsyncWorldEdit, AuthMe, BetterRTP, ChatControl, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, CrazyAuctions, EzClans, FarmLimiter, HackedCore*, HackedServer*, HeadDatabase*, LagAssist, LuckPerms, Marriage, PlaceholderAPI, ProtocolLib, PvPManager, SAML, SkinsRestorer, Spartan, SurvivalTweaks, TAB, TimeIsMoney*, Vault, ViaBackwards, ViaVersion, VillagerLobotomizatorNator, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags
```

**Version**

```
This server is running Purpur version git-Purpur-828 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Purpur-822 (MC: 1.16.4)
You are running the latest version
```

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Could be related to the recent upstream commit to Tuinity.

**Additional context**
Server was stopped with `/stop` command without any errors. The error occured shortly after restart (region was close to spawn).

**Comment by MrIvanPlays** [comment]
> reload 

:eyes:

**Comment by radiant-ai** [comment]
> > reload
> 
> 👀

corrected my wording

**Comment by montlikadani** [comment]
Related to https://github.com/PaperMC/Paper/issues/4758
Probably Paper will investigate this issue

**Comment by radiant-ai** [comment]
I guess I can close this since it is an very Upstream issue and the commit was already reverted.
