### ISSUE TITLE
Entity threw exception at xxx java.lang.OutOfMemoryError: Compressed class space

### ISSUE THREAD

**Issue by candy999** [pl3xgaming/Purpur#992]
### Timings link

https://timings.aikar.co/?id=b5e51e1c7b3a48c3b63c3a8f5ebf97ec

### Stack trace

[23:33:30] [Server thread/ERROR]: Entity threw exception at chaos_the_end:4828.369670175676,102.33958261497625,903.5
java.lang.OutOfMemoryError: Compressed class space
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at org.mozilla.javascript.DefiningClassLoader.defineClass(DefiningClassLoader.java:27) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.optimizer.Codegen.defineClass(Codegen.java:130) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.optimizer.Codegen.createScriptObject(Codegen.java:85) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Context.compileImpl(Context.java:2534) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Context.compileString(Context.java:1476) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Context.compileString(Context.java:1465) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1216) ~[rhino-1.7.7.1.jar:1.7.7.1]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.getRuntimeScope(RhinoScriptEngine.java:313) ~[rhino-js-engine-1.7.7.1.jar:?]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:156) ~[rhino-js-engine-1.7.7.1.jar:?]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:198) ~[rhino-js-engine-1.7.7.1.jar:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
	at net.minecraft.world.entity.monster.Shulker.hitByShulkerBullet(Shulker.java:537) ~[?:?]
	at net.minecraft.world.entity.monster.Shulker.hurt(Shulker.java:515) ~[?:?]
	at net.minecraft.world.entity.projectile.ShulkerBullet.onHitEntity(ShulkerBullet.java:309) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[?:?]
	at net.minecraft.world.entity.projectile.ShulkerBullet.onHit(ShulkerBullet.java:329) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[?:?]
	at net.minecraft.world.entity.projectile.ShulkerBullet.tick(ShulkerBullet.java:247) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1218) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:697) ~[?:?]
	at net.minecraft.server.level.WorldServer$$Lambda$7583/0x00000008023ac000.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:675) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1623]
	at net.minecraft.server.MinecraftServer$$Lambda$4172/0x00000008015097f0.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:33:34] [Thread-15/WARN]: java.lang.OutOfMemoryError: Compressed class space
[23:33:34] [Thread-15/WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.lang.System$2.defineClass(System.java:2303)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:66)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:401)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:395)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.security.AccessController.executePrivileged(AccessController.java:776)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:394)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:112)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
[23:33:34] [Thread-15/WARN]: 	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:455)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1574)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:543)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:515)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.security.AccessController.executePrivileged(AccessController.java:776)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:515)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:409)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1147)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
[23:33:34] [Thread-15/WARN]: 	at CoreProtect.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:25)
[23:33:34] [Thread-15/WARN]: 	at CoreProtect.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[23:33:34] [Thread-15/WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[23:33:34] [Thread-15/WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:195)
[23:33:34] [Thread-15/WARN]: 	at CoreProtect.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[23:33:34] [Thread-15/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### Actions to reproduce (if known)

go to map chaos_the_end:4828.369670175676,102.33958261497625,903.5 
activation Shulker get crash.

### Purpur version

1613~1628

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by candy999** [comment]
I retrieve May 1 to June 5 have crash 8 time.
![image](https://user-images.githubusercontent.com/2743971/172059567-6d774b3d-a8bf-4a36-9580-25f8fdb60c83.png)

**Comment by SageSphinx63920** [comment]
Seems like your server is running out of RAM

**Comment by candy999** [comment]
out of RAM is go to map chaos_the_end:4828.369670175676,102.33958261497625,903.5
activation Shulker get it.
Compressed class space set 1GB still out of RAM and CPU 6x%(4C8T CPU)

**Comment by BillyGalbreath** [comment]
```java.lang.OutOfMemoryError: Compressed class space```

Compressed space is where classes are loaded. By default the JVM allocates 1GB of compressed space for this purpose. This means you are loading too many classes and filling up this space. This can happen if you unload/load plugins during runtime (with PlugMan, etc) too many times, etc. If that's the case, stop doing that and just /stop your server instead. If you really want to persist that behavior then you can increase the compressed space size with a JVM flag (`-XX:CompressedClassSpaceSize=2g`), but I implore you to not even consider this as an option.
