### ISSUE TITLE
[1.19-1634] Server crash when starting

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#997]
### Timings link

No

### Stack trace

```
Downloading mojang_1.19.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.3+7) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[10:08:50 INFO]: Building unoptimized datafixer
[10:08:52 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:08:52 INFO]: Found new data pack file/bukkit, loading it automatically
[10:08:53 INFO]: Loaded 7 recipes
[10:08:54 INFO]: Starting minecraft server version 1.19
[10:08:54 INFO]: Loading properties
[10:08:54 INFO]: This server is running Purpur version git-Purpur-1634 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 2cedce1 on HEAD)
[10:08:54 INFO]: Server Ping Player Sample Count: 12
[10:08:54 INFO]: Using 4 threads for Netty based IO
[10:08:54 WARN]: [io.papermc.paper.configuration.PaperConfigurations] The world config file for __world_defaults__ didn't have a version set, assuming latest
[10:08:54 ERROR]: Unable to load server configuration
java.lang.UnsupportedOperationException: null
        at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?]
        at org.purpurmc.purpur.PurpurConfig.seedSettings(PurpurConfig.java:235) ~[purpur-1.19.jar:git-Purpur-1634]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.purpurmc.purpur.PurpurConfig.readConfig(PurpurConfig.java:103) ~[purpur-1.19.jar:git-Purpur-1634]
        at org.purpurmc.purpur.PurpurConfig.init(PurpurConfig.java:78) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:228) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[purpur-1.19.jar:git-Purpur-1634]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:08:54 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[purpur-1.19.jar:git-Purpur-1634]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:08:54 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1718) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:61) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1717) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[purpur-1.19.jar:git-Purpur-1634]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[purpur-1.19.jar:git-Purpur-1634]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:08:54 ERROR]: This crash report has been saved to: C:\Users\14868\Desktop\MCServer\Purpur-1.19\.\crash-reports\crash-2022-06-10_10.08.54-server.txt
[10:08:54 INFO]: Stopping server
[10:08:54 INFO]: Saving players
[10:08:54 INFO]: Saving worlds
[10:08:54 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[10:08:54 INFO]: Flushing Chunk IO
>
```

### Actions to reproduce (if known)

1.download purpur-1.19-1634.jar.
2.put the jar file and eula.txt and server.properties together.
my server.properties:
difficulty=3
max-players=2000
view-distance=12
online-mode=false
level-type=amplified

(there is no new line after the file)
3. launch with java -XX:ActiveProcessorCount=1 -server -Xmx800M -Xms800M -jar purpur-1.19-1634.jar nogui

### Purpur version

[10:08:54 INFO]: This server is running Purpur version git-Purpur-1634 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 2cedce1 on HEAD)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by ghost** [comment]
[crash-2022-06-10_10.08.54-server.txt](https://github.com/PurpurMC/Purpur/files/8875242/crash-2022-06-10_10.08.54-server.txt)
crash report file.

**Comment by katekerllenevich** [comment]
Known issue:
> this crash will be fixed once i get the new config system out
it has to do with initialization order
and the new system should fix that
